# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1600, 900))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.worker_portal_tab = QtWidgets.QWidget()
        self.worker_portal_tab.setObjectName("worker_portal_tab")
        self.portal3 = QtWidgets.QPushButton(self.worker_portal_tab)
        self.portal3.setGeometry(QtCore.QRect(50, 380, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.portal3.setFont(font)
        self.portal3.setObjectName("portal3")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.portal3)
        self.portal4 = QtWidgets.QPushButton(self.worker_portal_tab)
        self.portal4.setGeometry(QtCore.QRect(520, 380, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.portal4.setFont(font)
        self.portal4.setObjectName("portal4")
        self.buttonGroup.addButton(self.portal4)
        self.portal2 = QtWidgets.QPushButton(self.worker_portal_tab)
        self.portal2.setGeometry(QtCore.QRect(520, 130, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.portal2.setFont(font)
        self.portal2.setObjectName("portal2")
        self.buttonGroup.addButton(self.portal2)
        self.portal1 = QtWidgets.QPushButton(self.worker_portal_tab)
        self.portal1.setGeometry(QtCore.QRect(50, 130, 231, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.portal1.setFont(font)
        self.portal1.setObjectName("portal1")
        self.buttonGroup.addButton(self.portal1)
        self.label_2 = QtWidgets.QLabel(self.worker_portal_tab)
        self.label_2.setGeometry(QtCore.QRect(520, 70, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.worker_portal_tab)
        self.label.setGeometry(QtCore.QRect(50, 70, 81, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.worker_portal_tab)
        self.label_3.setGeometry(QtCore.QRect(50, 320, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.worker_portal_tab)
        self.label_4.setGeometry(QtCore.QRect(520, 320, 81, 16))
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.worker_portal_tab)
        self.frame.setGeometry(QtCore.QRect(520, 340, 231, 41))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background : rgb(255, 255, 255);\n"
"border-style : solid;\n"
"border-color: rgb(170, 255, 255);\n"
"border-width : 2px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Current_worker4 = QtWidgets.QLabel(self.frame)
        self.Current_worker4.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Current_worker4.setFont(font)
        self.Current_worker4.setText("")
        self.Current_worker4.setObjectName("Current_worker4")
        self.frame_4 = QtWidgets.QFrame(self.worker_portal_tab)
        self.frame_4.setGeometry(QtCore.QRect(50, 90, 231, 41))
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("background : rgb(255, 255, 255);\n"
"border-style : solid;\n"
"border-color: rgb(170, 255, 255);\n"
"border-width : 2px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.Current_worker1 = QtWidgets.QLabel(self.frame_4)
        self.Current_worker1.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Current_worker1.setFont(font)
        self.Current_worker1.setText("")
        self.Current_worker1.setObjectName("Current_worker1")
        self.frame_3 = QtWidgets.QFrame(self.worker_portal_tab)
        self.frame_3.setGeometry(QtCore.QRect(520, 90, 231, 41))
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("background : rgb(255, 255, 255);\n"
"border-style : solid;\n"
"border-color: rgb(170, 255, 255);\n"
"border-width : 2px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.Current_worker2 = QtWidgets.QLabel(self.frame_3)
        self.Current_worker2.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Current_worker2.setFont(font)
        self.Current_worker2.setText("")
        self.Current_worker2.setObjectName("Current_worker2")
        self.frame_2 = QtWidgets.QFrame(self.worker_portal_tab)
        self.frame_2.setGeometry(QtCore.QRect(50, 340, 231, 41))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("background : rgb(255, 255, 255);\n"
"border-style : solid;\n"
"border-color: rgb(170, 255, 255);\n"
"border-width : 2px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Current_worker3 = QtWidgets.QLabel(self.frame_2)
        self.Current_worker3.setGeometry(QtCore.QRect(0, 0, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Current_worker3.setFont(font)
        self.Current_worker3.setText("")
        self.Current_worker3.setObjectName("Current_worker3")
        self.tabWidget.addTab(self.worker_portal_tab, "")
        self.resistance_tab = QtWidgets.QWidget()
        self.resistance_tab.setObjectName("resistance_tab")
        self.box_pos_1 = QtWidgets.QGroupBox(self.resistance_tab)
        self.box_pos_1.setGeometry(QtCore.QRect(120, 120, 200, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.box_pos_1.setFont(font)
        self.box_pos_1.setAlignment(QtCore.Qt.AlignCenter)
        self.box_pos_1.setObjectName("box_pos_1")
        self.input_1_ii = QtWidgets.QLineEdit(self.box_pos_1)
        self.input_1_ii.setGeometry(QtCore.QRect(120, 80, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_1_ii.setFont(font)
        self.input_1_ii.setInputMask("")
        self.input_1_ii.setObjectName("input_1_ii")
        self.label_1_ii = QtWidgets.QLabel(self.box_pos_1)
        self.label_1_ii.setGeometry(QtCore.QRect(100, 80, 15, 25))
        self.label_1_ii.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1_ii.setObjectName("label_1_ii")
        self.led_1_ii = QtWidgets.QLabel(self.box_pos_1)
        self.led_1_ii.setGeometry(QtCore.QRect(10, 25, 20, 20))
        self.led_1_ii.setAutoFillBackground(True)
        self.led_1_ii.setText("")
        self.led_1_ii.setObjectName("led_1_ii")
        self.label_1_ii_3 = QtWidgets.QLabel(self.box_pos_1)
        self.label_1_ii_3.setGeometry(QtCore.QRect(100, 110, 15, 25))
        self.label_1_ii_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1_ii_3.setObjectName("label_1_ii_3")
        self.input_1_ii_3 = QtWidgets.QLineEdit(self.box_pos_1)
        self.input_1_ii_3.setGeometry(QtCore.QRect(120, 110, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_1_ii_3.setFont(font)
        self.input_1_ii_3.setInputMask("")
        self.input_1_ii_3.setObjectName("input_1_ii_3")
        self.label_1_ii_4 = QtWidgets.QLabel(self.box_pos_1)
        self.label_1_ii_4.setGeometry(QtCore.QRect(0, 80, 15, 25))
        self.label_1_ii_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1_ii_4.setObjectName("label_1_ii_4")
        self.input_1_ii_4 = QtWidgets.QLineEdit(self.box_pos_1)
        self.input_1_ii_4.setGeometry(QtCore.QRect(20, 80, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_1_ii_4.setFont(font)
        self.input_1_ii_4.setInputMask("")
        self.input_1_ii_4.setObjectName("input_1_ii_4")
        self.label_1_ii_5 = QtWidgets.QLabel(self.box_pos_1)
        self.label_1_ii_5.setGeometry(QtCore.QRect(0, 110, 15, 25))
        self.label_1_ii_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_1_ii_5.setObjectName("label_1_ii_5")
        self.input_1_ii_5 = QtWidgets.QLineEdit(self.box_pos_1)
        self.input_1_ii_5.setGeometry(QtCore.QRect(10, 110, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.input_1_ii_5.setFont(font)
        self.input_1_ii_5.setInputMask("")
        self.input_1_ii_5.setObjectName("input_1_ii_5")
        self.label_1_ii_6 = QtWidgets.QLabel(self.box_pos_1)
        self.label_1_ii_6.setGeometry(QtCore.QRect(0, 30, 201, 25))
        self.label_1_ii_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_ii_6.setObjectName("label_1_ii_6")
        self.workerID = QtWidgets.QGroupBox(self.resistance_tab)
        self.workerID.setGeometry(QtCore.QRect(420, 100, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.workerID.setFont(font)
        self.workerID.setObjectName("workerID")
        self.workerID_text = QtWidgets.QLineEdit(self.workerID)
        self.workerID_text.setGeometry(QtCore.QRect(10, 25, 180, 40))
        self.workerID_text.setInputMask("")
        self.workerID_text.setObjectName("workerID_text")
        self.palletID = QtWidgets.QGroupBox(self.resistance_tab)
        self.palletID.setGeometry(QtCore.QRect(400, 250, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.palletID.setFont(font)
        self.palletID.setObjectName("palletID")
        self.palletID_text = QtWidgets.QLineEdit(self.palletID)
        self.palletID_text.setGeometry(QtCore.QRect(10, 25, 180, 40))
        self.palletID_text.setInputMask("")
        self.palletID_text.setText("")
        self.palletID_text.setObjectName("palletID_text")
        self.straw1ID = QtWidgets.QGroupBox(self.resistance_tab)
        self.straw1ID.setGeometry(QtCore.QRect(150, 300, 200, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.straw1ID.setFont(font)
        self.straw1ID.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.straw1ID.setObjectName("straw1ID")
        self.straw1ID_text = QtWidgets.QLineEdit(self.straw1ID)
        self.straw1ID_text.setGeometry(QtCore.QRect(10, 25, 180, 40))
        self.straw1ID_text.setInputMask("")
        self.straw1ID_text.setText("")
        self.straw1ID_text.setObjectName("straw1ID_text")
        self.collect_button = QtWidgets.QPushButton(self.resistance_tab)
        self.collect_button.setGeometry(QtCore.QRect(180, 20, 180, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.collect_button.setFont(font)
        self.collect_button.setObjectName("collect_button")
        self.reset_button = QtWidgets.QPushButton(self.resistance_tab)
        self.reset_button.setGeometry(QtCore.QRect(560, 10, 180, 80))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.reset_button.setFont(font)
        self.reset_button.setObjectName("reset_button")
        self.tabWidget.addTab(self.resistance_tab, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.portal3.setText(_translate("MainWindow", "Log In"))
        self.portal4.setText(_translate("MainWindow", "Log In"))
        self.portal2.setText(_translate("MainWindow", "Log In"))
        self.portal1.setText(_translate("MainWindow", "Log In"))
        self.label_2.setText(_translate("MainWindow", "Current Worker:"))
        self.label.setText(_translate("MainWindow", "Current Worker:"))
        self.label_3.setText(_translate("MainWindow", "Current Worker:"))
        self.label_4.setText(_translate("MainWindow", "Current Worker:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.worker_portal_tab), _translate("MainWindow", "Worker Portal"))
        self.box_pos_1.setTitle(_translate("MainWindow", "Position 1"))
        self.input_1_ii.setPlaceholderText(_translate("MainWindow", "Scan worker ID"))
        self.label_1_ii.setText(_translate("MainWindow", "ii:"))
        self.label_1_ii_3.setText(_translate("MainWindow", "ii:"))
        self.input_1_ii_3.setPlaceholderText(_translate("MainWindow", "Scan worker ID"))
        self.label_1_ii_4.setText(_translate("MainWindow", "ii:"))
        self.input_1_ii_4.setPlaceholderText(_translate("MainWindow", "Scan worker ID"))
        self.label_1_ii_5.setText(_translate("MainWindow", "ii:"))
        self.input_1_ii_5.setPlaceholderText(_translate("MainWindow", "Scan worker ID"))
        self.label_1_ii_6.setText(_translate("MainWindow", "st0001"))
        self.workerID.setTitle(_translate("MainWindow", "Worker ID"))
        self.workerID_text.setPlaceholderText(_translate("MainWindow", "Scan worker ID"))
        self.palletID.setTitle(_translate("MainWindow", "Pallet ID"))
        self.palletID_text.setPlaceholderText(_translate("MainWindow", "Scan pallet ID"))
        self.straw1ID.setTitle(_translate("MainWindow", "Position 1 Straw ID"))
        self.straw1ID_text.setPlaceholderText(_translate("MainWindow", "Scan 1st straw ID"))
        self.collect_button.setText(_translate("MainWindow", "Collect Data"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.resistance_tab), _translate("MainWindow", "Straw Prep"))

