# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\wire_tensioner_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(513, 506)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 470, 55, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_4.setObjectName("label_4")
        self.statuslabel = QtWidgets.QLabel(Dialog)
        self.statuslabel.setGeometry(QtCore.QRect(80, 470, 421, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.statuslabel.setFont(font)
        self.statuslabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.statuslabel.setObjectName("statuslabel")
        self.stackedWidget = QtWidgets.QStackedWidget(Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 90, 471, 281))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tension_harden = QtWidgets.QPushButton(self.page)
        self.tension_harden.setGeometry(QtCore.QRect(0, 100, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tension_harden.setFont(font)
        self.tension_harden.setCheckable(True)
        self.tension_harden.setObjectName("tension_harden")
        self.recordtension = QtWidgets.QPushButton(self.page)
        self.recordtension.setGeometry(QtCore.QRect(0, 160, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.recordtension.setFont(font)
        self.recordtension.setCheckable(True)
        self.recordtension.setObjectName("recordtension")
        self.next_straw = QtWidgets.QPushButton(self.page)
        self.next_straw.setGeometry(QtCore.QRect(1, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.next_straw.setFont(font)
        self.next_straw.setCheckable(True)
        self.next_straw.setObjectName("next_straw")
        self.topcheck = QtWidgets.QCheckBox(self.page)
        self.topcheck.setGeometry(QtCore.QRect(10, 23, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topcheck.sizePolicy().hasHeightForWidth())
        self.topcheck.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.topcheck.setFont(font)
        self.topcheck.setObjectName("topcheck")
        self.bottomcheck = QtWidgets.QCheckBox(self.page)
        self.bottomcheck.setGeometry(QtCore.QRect(10, 50, 121, 20))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomcheck.sizePolicy().hasHeightForWidth())
        self.bottomcheck.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bottomcheck.setFont(font)
        self.bottomcheck.setObjectName("bottomcheck")
        self.resetmotor = QtWidgets.QPushButton(self.page)
        self.resetmotor.setGeometry(QtCore.QRect(160, 150, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resetmotor.setFont(font)
        self.resetmotor.setCheckable(True)
        self.resetmotor.setObjectName("resetmotor")
        self.tension_only = QtWidgets.QPushButton(self.page)
        self.tension_only.setGeometry(QtCore.QRect(160, 100, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tension_only.setFont(font)
        self.tension_only.setCheckable(True)
        self.tension_only.setObjectName("tension_only")
        self.tarebutton = QtWidgets.QPushButton(self.page)
        self.tarebutton.setGeometry(QtCore.QRect(290, 100, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tarebutton.setFont(font)
        self.tarebutton.setCheckable(True)
        self.tarebutton.setObjectName("tarebutton")
        self.setcalbutton = QtWidgets.QPushButton(self.page)
        self.setcalbutton.setGeometry(QtCore.QRect(290, 150, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setcalbutton.setFont(font)
        self.setcalbutton.setCheckable(True)
        self.setcalbutton.setObjectName("setcalbutton")
        self.recordlabel = QtWidgets.QLabel(self.page)
        self.recordlabel.setGeometry(QtCore.QRect(0, 260, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.recordlabel.setFont(font)
        self.recordlabel.setText("")
        self.recordlabel.setObjectName("recordlabel")
        self.calibfactor_2 = QtWidgets.QLabel(self.page)
        self.calibfactor_2.setGeometry(QtCore.QRect(300, 290, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.calibfactor_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calibfactor_2.setFont(font)
        self.calibfactor_2.setAutoFillBackground(True)
        self.calibfactor_2.setFrameShape(QtWidgets.QFrame.Box)
        self.calibfactor_2.setObjectName("calibfactor_2")
        self.tensionlabel = QtWidgets.QLabel(self.page)
        self.tensionlabel.setGeometry(QtCore.QRect(170, 50, 101, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tensionlabel.sizePolicy().hasHeightForWidth())
        self.tensionlabel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.tensionlabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tensionlabel.setFont(font)
        self.tensionlabel.setAutoFillBackground(False)
        self.tensionlabel.setFrameShape(QtWidgets.QFrame.Box)
        self.tensionlabel.setObjectName("tensionlabel")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(170, 22, 97, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(160, 200, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.tension_replaced = QtWidgets.QPushButton(self.frame)
        self.tension_replaced.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tension_replaced.setFont(font)
        self.tension_replaced.setCheckable(True)
        self.tension_replaced.setObjectName("tension_replaced")
        self.retension_val = QtWidgets.QLineEdit(self.frame)
        self.retension_val.setGeometry(QtCore.QRect(240, 10, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.retension_val.setFont(font)
        self.retension_val.setObjectName("retension_val")
        self.frame.raise_()
        self.tension_harden.raise_()
        self.recordtension.raise_()
        self.next_straw.raise_()
        self.topcheck.raise_()
        self.bottomcheck.raise_()
        self.resetmotor.raise_()
        self.tension_only.raise_()
        self.tarebutton.raise_()
        self.setcalbutton.raise_()
        self.recordlabel.raise_()
        self.calibfactor_2.raise_()
        self.tensionlabel.raise_()
        self.label.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.layoutWidget_2 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 143, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.caliblabel = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.caliblabel.setFont(font)
        self.caliblabel.setObjectName("caliblabel")
        self.verticalLayout_6.addWidget(self.caliblabel)
        self.calibmode = QtWidgets.QLabel(self.layoutWidget_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.calibmode.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calibmode.setFont(font)
        self.calibmode.setAutoFillBackground(True)
        self.calibmode.setFrameShape(QtWidgets.QFrame.Box)
        self.calibmode.setObjectName("calibmode")
        self.verticalLayout_6.addWidget(self.calibmode)
        self.tare = QtWidgets.QPushButton(self.page_2)
        self.tare.setGeometry(QtCore.QRect(10, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tare.setFont(font)
        self.tare.setCheckable(True)
        self.tare.setObjectName("tare")
        self.setbutton = QtWidgets.QPushButton(self.page_2)
        self.setbutton.setGeometry(QtCore.QRect(10, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setbutton.setFont(font)
        self.setbutton.setCheckable(True)
        self.setbutton.setObjectName("setbutton")
        self.layoutWidget_4 = QtWidgets.QWidget(self.page_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(170, 90, 139, 61))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.caliblabel_3 = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.caliblabel_3.setFont(font)
        self.caliblabel_3.setObjectName("caliblabel_3")
        self.verticalLayout_8.addWidget(self.caliblabel_3)
        self.loadcellreading = QtWidgets.QLabel(self.layoutWidget_4)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.loadcellreading.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loadcellreading.setFont(font)
        self.loadcellreading.setAutoFillBackground(True)
        self.loadcellreading.setFrameShape(QtWidgets.QFrame.Box)
        self.loadcellreading.setObjectName("loadcellreading")
        self.verticalLayout_8.addWidget(self.loadcellreading)
        self.tension_mode = QtWidgets.QPushButton(self.page_2)
        self.tension_mode.setGeometry(QtCore.QRect(310, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tension_mode.setFont(font)
        self.tension_mode.setCheckable(True)
        self.tension_mode.setObjectName("tension_mode")
        self.stackedWidget.addWidget(self.page_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.strawnumbox = QtWidgets.QSpinBox(Dialog)
        self.strawnumbox.setGeometry(QtCore.QRect(28, 50, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strawnumbox.sizePolicy().hasHeightForWidth())
        self.strawnumbox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.strawnumbox.setFont(font)
        self.strawnumbox.setObjectName("strawnumbox")
        self.caliblabel_2 = QtWidgets.QLabel(Dialog)
        self.caliblabel_2.setGeometry(QtCore.QRect(190, 20, 137, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.caliblabel_2.setFont(font)
        self.caliblabel_2.setObjectName("caliblabel_2")
        self.calibfactor = QtWidgets.QLabel(Dialog)
        self.calibfactor.setGeometry(QtCore.QRect(190, 50, 131, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.calibfactor.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.calibfactor.setFont(font)
        self.calibfactor.setAutoFillBackground(False)
        self.calibfactor.setFrameShape(QtWidgets.QFrame.Box)
        self.calibfactor.setObjectName("calibfactor")
        self.caliblabel_4 = QtWidgets.QLabel(Dialog)
        self.caliblabel_4.setGeometry(QtCore.QRect(20, 370, 137, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.caliblabel_4.setFont(font)
        self.caliblabel_4.setObjectName("caliblabel_4")
        self.selectWireAlignment = QtWidgets.QComboBox(Dialog)
        self.selectWireAlignment.setGeometry(QtCore.QRect(250, 400, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectWireAlignment.setFont(font)
        self.selectWireAlignment.setObjectName("selectWireAlignment")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectWireAlignment.addItem("")
        self.selectContinuity = QtWidgets.QComboBox(Dialog)
        self.selectContinuity.setGeometry(QtCore.QRect(20, 400, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectContinuity.setFont(font)
        self.selectContinuity.setObjectName("selectContinuity")
        self.selectContinuity.addItem("")
        self.selectContinuity.addItem("")
        self.selectContinuity.addItem("")
        self.selectContinuity.addItem("")
        self.selectContinuity.addItem("")
        self.strawtimelabel = QtWidgets.QLabel(Dialog)
        self.strawtimelabel.setGeometry(QtCore.QRect(350, 50, 91, 31))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.strawtimelabel.sizePolicy().hasHeightForWidth()
        )
        self.strawtimelabel.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        self.strawtimelabel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.strawtimelabel.setFont(font)
        self.strawtimelabel.setAutoFillBackground(False)
        self.strawtimelabel.setFrameShape(QtWidgets.QFrame.Box)
        self.strawtimelabel.setObjectName("strawtimelabel")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(350, 22, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.raise_()
        self.label_4.raise_()
        self.statuslabel.raise_()
        self.label_2.raise_()
        self.strawnumbox.raise_()
        self.caliblabel_2.raise_()
        self.calibfactor.raise_()
        self.caliblabel_4.raise_()
        self.selectWireAlignment.raise_()
        self.selectContinuity.raise_()
        self.strawtimelabel.raise_()
        self.label_9.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Status:"))
        self.statuslabel.setText(_translate("Dialog", "TextLabel"))
        self.tension_harden.setText(
            _translate("Dialog", "Work Harden and \n" "Tension Wire")
        )
        self.recordtension.setText(_translate("Dialog", "Save"))
        self.next_straw.setText(_translate("Dialog", "Next Straw"))
        self.topcheck.setText(_translate("Dialog", "Top Row"))
        self.bottomcheck.setText(_translate("Dialog", "Bottom Row"))
        self.resetmotor.setText(_translate("Dialog", "Reset Motor"))
        self.tension_only.setText(_translate("Dialog", "Tension Wire"))
        self.tarebutton.setText(_translate("Dialog", "Tare Load Cell (50g)"))
        self.setcalbutton.setText(_translate("Dialog", "Set Calibration (100g)"))
        self.calibfactor_2.setText(_translate("Dialog", "0"))
        self.tensionlabel.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Wire Tension"))
        self.tension_replaced.setText(_translate("Dialog", "Tension Replaced Wire (g)"))
        self.retension_val.setText(_translate("Dialog", "85"))
        self.caliblabel.setText(_translate("Dialog", "Calibration mode"))
        self.calibmode.setText(_translate("Dialog", "standby"))
        self.tare.setText(_translate("Dialog", "Tare: Hang 50g"))
        self.setbutton.setText(_translate("Dialog", "Set: Hang 100g"))
        self.caliblabel_3.setText(_translate("Dialog", "Load Cell reading"))
        self.loadcellreading.setText(_translate("Dialog", "0"))
        self.tension_mode.setText(_translate("Dialog", "Tension Mode"))
        self.label_2.setText(_translate("Dialog", "Wire Number"))
        self.caliblabel_2.setText(_translate("Dialog", "Calibration Factor"))
        self.calibfactor.setText(_translate("Dialog", "0"))
        self.caliblabel_4.setText(_translate("Dialog", "Continuity"))
        self.selectWireAlignment.setItemText(0, _translate("Dialog", "Select"))
        self.selectWireAlignment.setItemText(1, _translate("Dialog", "Short, Top"))
        self.selectWireAlignment.setItemText(2, _translate("Dialog", "Short, Middle"))
        self.selectWireAlignment.setItemText(3, _translate("Dialog", "Short, Bottom"))
        self.selectWireAlignment.setItemText(4, _translate("Dialog", "Middle, Top"))
        self.selectWireAlignment.setItemText(5, _translate("Dialog", "True Middle"))
        self.selectWireAlignment.setItemText(6, _translate("Dialog", "Middle, Bottom"))
        self.selectWireAlignment.setItemText(7, _translate("Dialog", "Long, Top"))
        self.selectWireAlignment.setItemText(8, _translate("Dialog", "Long, Middle"))
        self.selectWireAlignment.setItemText(9, _translate("Dialog", "Long, Bottom"))
        self.selectContinuity.setItemText(0, _translate("Dialog", "Select"))
        self.selectContinuity.setItemText(
            1, _translate("Dialog", "Pass: No Continuity")
        )
        self.selectContinuity.setItemText(
            2, _translate("Dialog", "Fail: Right Continuity")
        )
        self.selectContinuity.setItemText(
            3, _translate("Dialog", "Fail: Left Continuity")
        )
        self.selectContinuity.setItemText(
            4, _translate("Dialog", "Fail: Both Continuity")
        )
        self.strawtimelabel.setText(_translate("Dialog", "0"))
        self.label_9.setText(_translate("Dialog", "Wire Timer"))
