# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Status1Board.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1200)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.widget = QtWidgets.QWidget(self.centralWidget)
        self.widget.setGeometry(QtCore.QRect(90, 530, 120, 80))
        self.widget.setObjectName("widget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1371, 941))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 70, 671, 61))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.prog1 = QtWidgets.QProgressBar(self.frame)
        self.prog1.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog1.setProperty("value", 0)
        self.prog1.setObjectName("prog1")
        self.pos1 = QtWidgets.QComboBox(self.frame)
        self.pos1.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos1.setObjectName("pos1")
        self.pos1.addItem("")
        self.pos1.addItem("")
        self.pal_1 = QtWidgets.QPushButton(self.frame)
        self.pal_1.setGeometry(QtCore.QRect(10, 12, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_1.setFont(font)
        self.pal_1.setObjectName("pal_1")
        self.palbuttons = QtWidgets.QButtonGroup(MainWindow)
        self.palbuttons.setObjectName("palbuttons")
        self.palbuttons.addButton(self.pal_1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(60, 20, 511, 20))
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(90, 20, 20, 881))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(560, 20, 20, 881))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(self.tab)
        self.line_4.setGeometry(QtCore.QRect(140, 20, 20, 881))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(190, 20, 20, 881))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_5 = QtWidgets.QFrame(self.tab)
        self.line_5.setGeometry(QtCore.QRect(350, 20, 20, 881))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(280, 20, 20, 881))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab)
        self.line_7.setGeometry(QtCore.QRect(390, 20, 20, 881))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.next1 = QtWidgets.QPushButton(self.tab)
        self.next1.setGeometry(QtCore.QRect(600, 90, 31, 23))
        self.next1.setObjectName("next1")
        self.nextbuttons = QtWidgets.QButtonGroup(MainWindow)
        self.nextbuttons.setObjectName("nextbuttons")
        self.nextbuttons.addButton(self.next1)
        self.last1 = QtWidgets.QPushButton(self.tab)
        self.last1.setGeometry(QtCore.QRect(570, 90, 31, 23))
        self.last1.setObjectName("last1")
        self.lastbuttons = QtWidgets.QButtonGroup(MainWindow)
        self.lastbuttons.setObjectName("lastbuttons")
        self.lastbuttons.addButton(self.last1)
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 140, 671, 61))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.prog2 = QtWidgets.QProgressBar(self.frame_2)
        self.prog2.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog2.setProperty("value", 0)
        self.prog2.setObjectName("prog2")
        self.pos2 = QtWidgets.QComboBox(self.frame_2)
        self.pos2.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos2.setObjectName("pos2")
        self.pos2.addItem("")
        self.pos2.addItem("")
        self.pal_2 = QtWidgets.QPushButton(self.frame_2)
        self.pal_2.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_2.setFont(font)
        self.pal_2.setObjectName("pal_2")
        self.palbuttons.addButton(self.pal_2)
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(10, 210, 671, 61))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.prog3 = QtWidgets.QProgressBar(self.frame_3)
        self.prog3.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog3.setProperty("value", 0)
        self.prog3.setObjectName("prog3")
        self.pos3 = QtWidgets.QComboBox(self.frame_3)
        self.pos3.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos3.setObjectName("pos3")
        self.pos3.addItem("")
        self.pos3.addItem("")
        self.pal_3 = QtWidgets.QPushButton(self.frame_3)
        self.pal_3.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_3.setFont(font)
        self.pal_3.setObjectName("pal_3")
        self.palbuttons.addButton(self.pal_3)
        self.frame_7 = QtWidgets.QFrame(self.tab)
        self.frame_7.setGeometry(QtCore.QRect(10, 280, 671, 61))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.prog4 = QtWidgets.QProgressBar(self.frame_7)
        self.prog4.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog4.setProperty("value", 0)
        self.prog4.setObjectName("prog4")
        self.pos4 = QtWidgets.QComboBox(self.frame_7)
        self.pos4.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos4.setObjectName("pos4")
        self.pos4.addItem("")
        self.pos4.addItem("")
        self.pal_4 = QtWidgets.QPushButton(self.frame_7)
        self.pal_4.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_4.setFont(font)
        self.pal_4.setObjectName("pal_4")
        self.palbuttons.addButton(self.pal_4)
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(10, 350, 671, 61))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.prog5 = QtWidgets.QProgressBar(self.frame_6)
        self.prog5.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog5.setProperty("value", 0)
        self.prog5.setObjectName("prog5")
        self.pos5 = QtWidgets.QComboBox(self.frame_6)
        self.pos5.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos5.setObjectName("pos5")
        self.pos5.addItem("")
        self.pos5.addItem("")
        self.pal_5 = QtWidgets.QPushButton(self.frame_6)
        self.pal_5.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_5.setFont(font)
        self.pal_5.setObjectName("pal_5")
        self.palbuttons.addButton(self.pal_5)
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(10, 420, 671, 61))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.prog6 = QtWidgets.QProgressBar(self.frame_5)
        self.prog6.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog6.setProperty("value", 0)
        self.prog6.setObjectName("prog6")
        self.pos6 = QtWidgets.QComboBox(self.frame_5)
        self.pos6.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos6.setObjectName("pos6")
        self.pos6.addItem("")
        self.pos6.addItem("")
        self.pal_6 = QtWidgets.QPushButton(self.frame_5)
        self.pal_6.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_6.setFont(font)
        self.pal_6.setObjectName("pal_6")
        self.palbuttons.addButton(self.pal_6)
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(10, 490, 671, 61))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.prog7 = QtWidgets.QProgressBar(self.frame_4)
        self.prog7.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog7.setProperty("value", 0)
        self.prog7.setObjectName("prog7")
        self.pos7 = QtWidgets.QComboBox(self.frame_4)
        self.pos7.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos7.setObjectName("pos7")
        self.pos7.addItem("")
        self.pos7.addItem("")
        self.pal_7 = QtWidgets.QPushButton(self.frame_4)
        self.pal_7.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_7.setFont(font)
        self.pal_7.setObjectName("pal_7")
        self.palbuttons.addButton(self.pal_7)
        self.last2 = QtWidgets.QPushButton(self.tab)
        self.last2.setGeometry(QtCore.QRect(570, 160, 31, 23))
        self.last2.setObjectName("last2")
        self.lastbuttons.addButton(self.last2)
        self.next2 = QtWidgets.QPushButton(self.tab)
        self.next2.setGeometry(QtCore.QRect(600, 160, 31, 23))
        self.next2.setObjectName("next2")
        self.nextbuttons.addButton(self.next2)
        self.last3 = QtWidgets.QPushButton(self.tab)
        self.last3.setGeometry(QtCore.QRect(570, 230, 31, 23))
        self.last3.setObjectName("last3")
        self.lastbuttons.addButton(self.last3)
        self.next3 = QtWidgets.QPushButton(self.tab)
        self.next3.setGeometry(QtCore.QRect(600, 230, 31, 23))
        self.next3.setObjectName("next3")
        self.nextbuttons.addButton(self.next3)
        self.last4 = QtWidgets.QPushButton(self.tab)
        self.last4.setGeometry(QtCore.QRect(570, 300, 31, 23))
        self.last4.setObjectName("last4")
        self.lastbuttons.addButton(self.last4)
        self.next4 = QtWidgets.QPushButton(self.tab)
        self.next4.setGeometry(QtCore.QRect(600, 300, 31, 23))
        self.next4.setObjectName("next4")
        self.nextbuttons.addButton(self.next4)
        self.last5 = QtWidgets.QPushButton(self.tab)
        self.last5.setGeometry(QtCore.QRect(570, 370, 31, 23))
        self.last5.setObjectName("last5")
        self.lastbuttons.addButton(self.last5)
        self.next5 = QtWidgets.QPushButton(self.tab)
        self.next5.setGeometry(QtCore.QRect(600, 370, 31, 23))
        self.next5.setObjectName("next5")
        self.nextbuttons.addButton(self.next5)
        self.last6 = QtWidgets.QPushButton(self.tab)
        self.last6.setGeometry(QtCore.QRect(570, 440, 31, 23))
        self.last6.setObjectName("last6")
        self.lastbuttons.addButton(self.last6)
        self.next6 = QtWidgets.QPushButton(self.tab)
        self.next6.setGeometry(QtCore.QRect(600, 440, 31, 23))
        self.next6.setObjectName("next6")
        self.nextbuttons.addButton(self.next6)
        self.last7 = QtWidgets.QPushButton(self.tab)
        self.last7.setGeometry(QtCore.QRect(570, 510, 31, 23))
        self.last7.setObjectName("last7")
        self.lastbuttons.addButton(self.last7)
        self.next7 = QtWidgets.QPushButton(self.tab)
        self.next7.setGeometry(QtCore.QRect(600, 510, 31, 23))
        self.next7.setObjectName("next7")
        self.nextbuttons.addButton(self.next7)
        self.frame_8 = QtWidgets.QFrame(self.tab)
        self.frame_8.setGeometry(QtCore.QRect(10, 560, 671, 61))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.prog8 = QtWidgets.QProgressBar(self.frame_8)
        self.prog8.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog8.setProperty("value", 0)
        self.prog8.setObjectName("prog8")
        self.next8 = QtWidgets.QPushButton(self.frame_8)
        self.next8.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next8.setObjectName("next8")
        self.nextbuttons.addButton(self.next8)
        self.last8 = QtWidgets.QPushButton(self.frame_8)
        self.last8.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last8.setObjectName("last8")
        self.lastbuttons.addButton(self.last8)
        self.pos8 = QtWidgets.QComboBox(self.frame_8)
        self.pos8.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos8.setObjectName("pos8")
        self.pos8.addItem("")
        self.pos8.addItem("")
        self.pal_8 = QtWidgets.QPushButton(self.frame_8)
        self.pal_8.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_8.setFont(font)
        self.pal_8.setObjectName("pal_8")
        self.palbuttons.addButton(self.pal_8)
        self.frame_9 = QtWidgets.QFrame(self.tab)
        self.frame_9.setGeometry(QtCore.QRect(10, 630, 671, 61))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.prog9 = QtWidgets.QProgressBar(self.frame_9)
        self.prog9.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog9.setProperty("value", 0)
        self.prog9.setObjectName("prog9")
        self.next9 = QtWidgets.QPushButton(self.frame_9)
        self.next9.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next9.setObjectName("next9")
        self.nextbuttons.addButton(self.next9)
        self.last9 = QtWidgets.QPushButton(self.frame_9)
        self.last9.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last9.setObjectName("last9")
        self.lastbuttons.addButton(self.last9)
        self.pos9 = QtWidgets.QComboBox(self.frame_9)
        self.pos9.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos9.setObjectName("pos9")
        self.pos9.addItem("")
        self.pos9.addItem("")
        self.pal_9 = QtWidgets.QPushButton(self.frame_9)
        self.pal_9.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_9.setFont(font)
        self.pal_9.setObjectName("pal_9")
        self.palbuttons.addButton(self.pal_9)
        self.frame_10 = QtWidgets.QFrame(self.tab)
        self.frame_10.setGeometry(QtCore.QRect(10, 700, 671, 61))
        self.frame_10.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.prog10 = QtWidgets.QProgressBar(self.frame_10)
        self.prog10.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog10.setProperty("value", 0)
        self.prog10.setObjectName("prog10")
        self.next10 = QtWidgets.QPushButton(self.frame_10)
        self.next10.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next10.setObjectName("next10")
        self.nextbuttons.addButton(self.next10)
        self.last10 = QtWidgets.QPushButton(self.frame_10)
        self.last10.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last10.setObjectName("last10")
        self.lastbuttons.addButton(self.last10)
        self.pos10 = QtWidgets.QComboBox(self.frame_10)
        self.pos10.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos10.setObjectName("pos10")
        self.pos10.addItem("")
        self.pos10.addItem("")
        self.pal_10 = QtWidgets.QPushButton(self.frame_10)
        self.pal_10.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_10.setFont(font)
        self.pal_10.setObjectName("pal_10")
        self.palbuttons.addButton(self.pal_10)
        self.frame_11 = QtWidgets.QFrame(self.tab)
        self.frame_11.setGeometry(QtCore.QRect(10, 770, 671, 61))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.prog11 = QtWidgets.QProgressBar(self.frame_11)
        self.prog11.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog11.setProperty("value", 0)
        self.prog11.setObjectName("prog11")
        self.next11 = QtWidgets.QPushButton(self.frame_11)
        self.next11.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next11.setObjectName("next11")
        self.nextbuttons.addButton(self.next11)
        self.last11 = QtWidgets.QPushButton(self.frame_11)
        self.last11.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last11.setObjectName("last11")
        self.lastbuttons.addButton(self.last11)
        self.pos11 = QtWidgets.QComboBox(self.frame_11)
        self.pos11.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos11.setObjectName("pos11")
        self.pos11.addItem("")
        self.pos11.addItem("")
        self.pal_11 = QtWidgets.QPushButton(self.frame_11)
        self.pal_11.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_11.setFont(font)
        self.pal_11.setObjectName("pal_11")
        self.palbuttons.addButton(self.pal_11)
        self.frame_12 = QtWidgets.QFrame(self.tab)
        self.frame_12.setGeometry(QtCore.QRect(10, 840, 671, 61))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.prog12 = QtWidgets.QProgressBar(self.frame_12)
        self.prog12.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog12.setProperty("value", 0)
        self.prog12.setObjectName("prog12")
        self.next12 = QtWidgets.QPushButton(self.frame_12)
        self.next12.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next12.setObjectName("next12")
        self.nextbuttons.addButton(self.next12)
        self.last12 = QtWidgets.QPushButton(self.frame_12)
        self.last12.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last12.setObjectName("last12")
        self.lastbuttons.addButton(self.last12)
        self.pos12 = QtWidgets.QComboBox(self.frame_12)
        self.pos12.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos12.setObjectName("pos12")
        self.pos12.addItem("")
        self.pos12.addItem("")
        self.pal_12 = QtWidgets.QPushButton(self.frame_12)
        self.pal_12.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_12.setFont(font)
        self.pal_12.setObjectName("pal_12")
        self.palbuttons.addButton(self.pal_12)
        self.line_8 = QtWidgets.QFrame(self.tab)
        self.line_8.setGeometry(QtCore.QRect(1030, 20, 20, 881))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(1070, 20, 20, 881))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab)
        self.line_10.setGeometry(QtCore.QRect(820, 20, 20, 881))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.frame_13 = QtWidgets.QFrame(self.tab)
        self.frame_13.setGeometry(QtCore.QRect(690, 560, 671, 61))
        self.frame_13.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.prog20 = QtWidgets.QProgressBar(self.frame_13)
        self.prog20.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog20.setProperty("value", 0)
        self.prog20.setObjectName("prog20")
        self.next20 = QtWidgets.QPushButton(self.frame_13)
        self.next20.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next20.setObjectName("next20")
        self.nextbuttons.addButton(self.next20)
        self.last20 = QtWidgets.QPushButton(self.frame_13)
        self.last20.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last20.setObjectName("last20")
        self.lastbuttons.addButton(self.last20)
        self.pos20 = QtWidgets.QComboBox(self.frame_13)
        self.pos20.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos20.setObjectName("pos20")
        self.pos20.addItem("")
        self.pos20.addItem("")
        self.pal_20 = QtWidgets.QPushButton(self.frame_13)
        self.pal_20.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_20.setFont(font)
        self.pal_20.setObjectName("pal_20")
        self.palbuttons.addButton(self.pal_20)
        self.frame_14 = QtWidgets.QFrame(self.tab)
        self.frame_14.setGeometry(QtCore.QRect(690, 350, 671, 61))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.prog17 = QtWidgets.QProgressBar(self.frame_14)
        self.prog17.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog17.setProperty("value", 0)
        self.prog17.setObjectName("prog17")
        self.pos17 = QtWidgets.QComboBox(self.frame_14)
        self.pos17.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos17.setObjectName("pos17")
        self.pos17.addItem("")
        self.pos17.addItem("")
        self.last17 = QtWidgets.QPushButton(self.frame_14)
        self.last17.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last17.setObjectName("last17")
        self.lastbuttons.addButton(self.last17)
        self.next17 = QtWidgets.QPushButton(self.frame_14)
        self.next17.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next17.setObjectName("next17")
        self.nextbuttons.addButton(self.next17)
        self.pal_17 = QtWidgets.QPushButton(self.frame_14)
        self.pal_17.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_17.setFont(font)
        self.pal_17.setObjectName("pal_17")
        self.palbuttons.addButton(self.pal_17)
        self.frame_15 = QtWidgets.QFrame(self.tab)
        self.frame_15.setGeometry(QtCore.QRect(690, 840, 671, 61))
        self.frame_15.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.prog24 = QtWidgets.QProgressBar(self.frame_15)
        self.prog24.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog24.setProperty("value", 0)
        self.prog24.setObjectName("prog24")
        self.next24 = QtWidgets.QPushButton(self.frame_15)
        self.next24.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next24.setObjectName("next24")
        self.nextbuttons.addButton(self.next24)
        self.last24 = QtWidgets.QPushButton(self.frame_15)
        self.last24.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last24.setObjectName("last24")
        self.lastbuttons.addButton(self.last24)
        self.pos24 = QtWidgets.QComboBox(self.frame_15)
        self.pos24.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos24.setObjectName("pos24")
        self.pos24.addItem("")
        self.pos24.addItem("")
        self.pal_24 = QtWidgets.QPushButton(self.frame_15)
        self.pal_24.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_24.setFont(font)
        self.pal_24.setObjectName("pal_24")
        self.palbuttons.addButton(self.pal_24)
        self.frame_16 = QtWidgets.QFrame(self.tab)
        self.frame_16.setGeometry(QtCore.QRect(690, 280, 671, 61))
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.prog16 = QtWidgets.QProgressBar(self.frame_16)
        self.prog16.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog16.setProperty("value", 0)
        self.prog16.setObjectName("prog16")
        self.pos16 = QtWidgets.QComboBox(self.frame_16)
        self.pos16.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos16.setObjectName("pos16")
        self.pos16.addItem("")
        self.pos16.addItem("")
        self.last16 = QtWidgets.QPushButton(self.frame_16)
        self.last16.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last16.setObjectName("last16")
        self.lastbuttons.addButton(self.last16)
        self.next16 = QtWidgets.QPushButton(self.frame_16)
        self.next16.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next16.setObjectName("next16")
        self.nextbuttons.addButton(self.next16)
        self.pal_16 = QtWidgets.QPushButton(self.frame_16)
        self.pal_16.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_16.setFont(font)
        self.pal_16.setObjectName("pal_16")
        self.palbuttons.addButton(self.pal_16)
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(740, 20, 511, 20))
        self.label_23.setObjectName("label_23")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(960, 20, 20, 881))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.frame_17 = QtWidgets.QFrame(self.tab)
        self.frame_17.setGeometry(QtCore.QRect(690, 420, 671, 61))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.prog18 = QtWidgets.QProgressBar(self.frame_17)
        self.prog18.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog18.setProperty("value", 0)
        self.prog18.setObjectName("prog18")
        self.pos18 = QtWidgets.QComboBox(self.frame_17)
        self.pos18.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos18.setObjectName("pos18")
        self.pos18.addItem("")
        self.pos18.addItem("")
        self.last18 = QtWidgets.QPushButton(self.frame_17)
        self.last18.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last18.setObjectName("last18")
        self.lastbuttons.addButton(self.last18)
        self.next18 = QtWidgets.QPushButton(self.frame_17)
        self.next18.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next18.setObjectName("next18")
        self.nextbuttons.addButton(self.next18)
        self.pal_18 = QtWidgets.QPushButton(self.frame_17)
        self.pal_18.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_18.setFont(font)
        self.pal_18.setObjectName("pal_18")
        self.palbuttons.addButton(self.pal_18)
        self.frame_18 = QtWidgets.QFrame(self.tab)
        self.frame_18.setGeometry(QtCore.QRect(690, 490, 671, 61))
        self.frame_18.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.prog19 = QtWidgets.QProgressBar(self.frame_18)
        self.prog19.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog19.setProperty("value", 0)
        self.prog19.setObjectName("prog19")
        self.pos19 = QtWidgets.QComboBox(self.frame_18)
        self.pos19.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos19.setObjectName("pos19")
        self.pos19.addItem("")
        self.pos19.addItem("")
        self.last19 = QtWidgets.QPushButton(self.frame_18)
        self.last19.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last19.setObjectName("last19")
        self.lastbuttons.addButton(self.last19)
        self.next19 = QtWidgets.QPushButton(self.frame_18)
        self.next19.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next19.setObjectName("next19")
        self.nextbuttons.addButton(self.next19)
        self.pal_19 = QtWidgets.QPushButton(self.frame_18)
        self.pal_19.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_19.setFont(font)
        self.pal_19.setObjectName("pal_19")
        self.palbuttons.addButton(self.pal_19)
        self.line_12 = QtWidgets.QFrame(self.tab)
        self.line_12.setGeometry(QtCore.QRect(1240, 20, 20, 881))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.tab)
        self.line_13.setGeometry(QtCore.QRect(870, 20, 20, 881))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.frame_19 = QtWidgets.QFrame(self.tab)
        self.frame_19.setGeometry(QtCore.QRect(690, 140, 671, 61))
        self.frame_19.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.prog14 = QtWidgets.QProgressBar(self.frame_19)
        self.prog14.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog14.setProperty("value", 0)
        self.prog14.setObjectName("prog14")
        self.pos14 = QtWidgets.QComboBox(self.frame_19)
        self.pos14.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos14.setObjectName("pos14")
        self.pos14.addItem("")
        self.pos14.addItem("")
        self.last14 = QtWidgets.QPushButton(self.frame_19)
        self.last14.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last14.setObjectName("last14")
        self.lastbuttons.addButton(self.last14)
        self.next14 = QtWidgets.QPushButton(self.frame_19)
        self.next14.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next14.setObjectName("next14")
        self.nextbuttons.addButton(self.next14)
        self.pal_14 = QtWidgets.QPushButton(self.frame_19)
        self.pal_14.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_14.setFont(font)
        self.pal_14.setObjectName("pal_14")
        self.palbuttons.addButton(self.pal_14)
        self.frame_20 = QtWidgets.QFrame(self.tab)
        self.frame_20.setGeometry(QtCore.QRect(690, 770, 671, 61))
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.prog23 = QtWidgets.QProgressBar(self.frame_20)
        self.prog23.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog23.setProperty("value", 0)
        self.prog23.setObjectName("prog23")
        self.next23 = QtWidgets.QPushButton(self.frame_20)
        self.next23.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next23.setObjectName("next23")
        self.nextbuttons.addButton(self.next23)
        self.last23 = QtWidgets.QPushButton(self.frame_20)
        self.last23.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last23.setObjectName("last23")
        self.lastbuttons.addButton(self.last23)
        self.pos23 = QtWidgets.QComboBox(self.frame_20)
        self.pos23.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos23.setObjectName("pos23")
        self.pos23.addItem("")
        self.pos23.addItem("")
        self.pal_23 = QtWidgets.QPushButton(self.frame_20)
        self.pal_23.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_23.setFont(font)
        self.pal_23.setObjectName("pal_23")
        self.palbuttons.addButton(self.pal_23)
        self.frame_21 = QtWidgets.QFrame(self.tab)
        self.frame_21.setGeometry(QtCore.QRect(690, 700, 671, 61))
        self.frame_21.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.prog22 = QtWidgets.QProgressBar(self.frame_21)
        self.prog22.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog22.setProperty("value", 0)
        self.prog22.setObjectName("prog22")
        self.next22 = QtWidgets.QPushButton(self.frame_21)
        self.next22.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next22.setObjectName("next22")
        self.nextbuttons.addButton(self.next22)
        self.last22 = QtWidgets.QPushButton(self.frame_21)
        self.last22.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last22.setObjectName("last22")
        self.lastbuttons.addButton(self.last22)
        self.pos22 = QtWidgets.QComboBox(self.frame_21)
        self.pos22.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos22.setObjectName("pos22")
        self.pos22.addItem("")
        self.pos22.addItem("")
        self.pal_22 = QtWidgets.QPushButton(self.frame_21)
        self.pal_22.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_22.setFont(font)
        self.pal_22.setObjectName("pal_22")
        self.palbuttons.addButton(self.pal_22)
        self.line_14 = QtWidgets.QFrame(self.tab)
        self.line_14.setGeometry(QtCore.QRect(770, 20, 20, 881))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.frame_22 = QtWidgets.QFrame(self.tab)
        self.frame_22.setGeometry(QtCore.QRect(690, 70, 671, 61))
        self.frame_22.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.prog13 = QtWidgets.QProgressBar(self.frame_22)
        self.prog13.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog13.setProperty("value", 0)
        self.prog13.setObjectName("prog13")
        self.pos13 = QtWidgets.QComboBox(self.frame_22)
        self.pos13.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos13.setObjectName("pos13")
        self.pos13.addItem("")
        self.pos13.addItem("")
        self.last13 = QtWidgets.QPushButton(self.frame_22)
        self.last13.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last13.setObjectName("last13")
        self.lastbuttons.addButton(self.last13)
        self.next13 = QtWidgets.QPushButton(self.frame_22)
        self.next13.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next13.setObjectName("next13")
        self.nextbuttons.addButton(self.next13)
        self.pal_13 = QtWidgets.QPushButton(self.frame_22)
        self.pal_13.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_13.setFont(font)
        self.pal_13.setObjectName("pal_13")
        self.palbuttons.addButton(self.pal_13)
        self.frame_23 = QtWidgets.QFrame(self.tab)
        self.frame_23.setGeometry(QtCore.QRect(690, 630, 671, 61))
        self.frame_23.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.prog21 = QtWidgets.QProgressBar(self.frame_23)
        self.prog21.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog21.setProperty("value", 0)
        self.prog21.setObjectName("prog21")
        self.next21 = QtWidgets.QPushButton(self.frame_23)
        self.next21.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next21.setObjectName("next21")
        self.nextbuttons.addButton(self.next21)
        self.last21 = QtWidgets.QPushButton(self.frame_23)
        self.last21.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last21.setObjectName("last21")
        self.lastbuttons.addButton(self.last21)
        self.pos21 = QtWidgets.QComboBox(self.frame_23)
        self.pos21.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos21.setObjectName("pos21")
        self.pos21.addItem("")
        self.pos21.addItem("")
        self.pal_21 = QtWidgets.QPushButton(self.frame_23)
        self.pal_21.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_21.setFont(font)
        self.pal_21.setObjectName("pal_21")
        self.palbuttons.addButton(self.pal_21)
        self.frame_24 = QtWidgets.QFrame(self.tab)
        self.frame_24.setGeometry(QtCore.QRect(690, 210, 671, 61))
        self.frame_24.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.prog15 = QtWidgets.QProgressBar(self.frame_24)
        self.prog15.setGeometry(QtCore.QRect(90, 20, 501, 23))
        self.prog15.setProperty("value", 0)
        self.prog15.setObjectName("prog15")
        self.pos15 = QtWidgets.QComboBox(self.frame_24)
        self.pos15.setGeometry(QtCore.QRect(630, 20, 31, 22))
        self.pos15.setObjectName("pos15")
        self.pos15.addItem("")
        self.pos15.addItem("")
        self.next15 = QtWidgets.QPushButton(self.frame_24)
        self.next15.setGeometry(QtCore.QRect(590, 20, 31, 23))
        self.next15.setObjectName("next15")
        self.nextbuttons.addButton(self.next15)
        self.last15 = QtWidgets.QPushButton(self.frame_24)
        self.last15.setGeometry(QtCore.QRect(560, 20, 31, 23))
        self.last15.setObjectName("last15")
        self.lastbuttons.addButton(self.last15)
        self.pal_15 = QtWidgets.QPushButton(self.frame_24)
        self.pal_15.setGeometry(QtCore.QRect(10, 10, 75, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pal_15.setFont(font)
        self.pal_15.setObjectName("pal_15")
        self.palbuttons.addButton(self.pal_15)
        self.line_15 = QtWidgets.QFrame(self.tab)
        self.line_15.setGeometry(QtCore.QRect(480, 20, 20, 881))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.tab)
        self.line_16.setGeometry(QtCore.QRect(1160, 20, 20, 881))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.frame.raise_()
        self.label_2.raise_()
        self.next1.raise_()
        self.last1.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_7.raise_()
        self.frame_6.raise_()
        self.frame_5.raise_()
        self.frame_4.raise_()
        self.last2.raise_()
        self.next2.raise_()
        self.last3.raise_()
        self.next3.raise_()
        self.last4.raise_()
        self.next4.raise_()
        self.last5.raise_()
        self.next5.raise_()
        self.last6.raise_()
        self.next6.raise_()
        self.last7.raise_()
        self.next7.raise_()
        self.frame_8.raise_()
        self.frame_9.raise_()
        self.frame_10.raise_()
        self.frame_11.raise_()
        self.frame_12.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line.raise_()
        self.line_7.raise_()
        self.line_2.raise_()
        self.frame_13.raise_()
        self.frame_14.raise_()
        self.frame_15.raise_()
        self.frame_16.raise_()
        self.label_23.raise_()
        self.frame_17.raise_()
        self.frame_18.raise_()
        self.frame_19.raise_()
        self.frame_20.raise_()
        self.frame_21.raise_()
        self.frame_22.raise_()
        self.frame_23.raise_()
        self.frame_24.raise_()
        self.line_8.raise_()
        self.line_13.raise_()
        self.line_9.raise_()
        self.line_10.raise_()
        self.line_11.raise_()
        self.line_12.raise_()
        self.line_14.raise_()
        self.line_15.raise_()
        self.line_16.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 1921, 881))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.currentWorkers = QtWidgets.QLabel(self.groupBox_3)
        self.currentWorkers.setGeometry(QtCore.QRect(30, 40, 1851, 811))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.currentWorkers.setFont(font)
        self.currentWorkers.setText("")
        self.currentWorkers.setObjectName("currentWorkers")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 950, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.stat1 = QtWidgets.QProgressBar(self.groupBox_11)
        self.stat1.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat1.setProperty("value", 0)
        self.stat1.setObjectName("stat1")
        self.disp1 = QtWidgets.QLCDNumber(self.groupBox_11)
        self.disp1.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp1.setPalette(palette)
        self.disp1.setAutoFillBackground(True)
        self.disp1.setObjectName("disp1")
        self.groupBox_10 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 1070, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.stat3 = QtWidgets.QProgressBar(self.groupBox_10)
        self.stat3.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat3.setProperty("value", 0)
        self.stat3.setObjectName("stat3")
        self.disp3 = QtWidgets.QLCDNumber(self.groupBox_10)
        self.disp3.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp3.setPalette(palette)
        self.disp3.setAutoFillBackground(True)
        self.disp3.setObjectName("disp3")
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 1130, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.stat4 = QtWidgets.QProgressBar(self.groupBox_15)
        self.stat4.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat4.setProperty("value", 0)
        self.stat4.setObjectName("stat4")
        self.disp4 = QtWidgets.QLCDNumber(self.groupBox_15)
        self.disp4.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp4.setPalette(palette)
        self.disp4.setAutoFillBackground(True)
        self.disp4.setObjectName("disp4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_9.setGeometry(QtCore.QRect(590, 1070, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.stat7 = QtWidgets.QProgressBar(self.groupBox_9)
        self.stat7.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat7.setProperty("value", 0)
        self.stat7.setObjectName("stat7")
        self.disp7 = QtWidgets.QLCDNumber(self.groupBox_9)
        self.disp7.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp7.setPalette(palette)
        self.disp7.setAutoFillBackground(True)
        self.disp7.setObjectName("disp7")
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_14.setGeometry(QtCore.QRect(590, 950, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.stat5 = QtWidgets.QProgressBar(self.groupBox_14)
        self.stat5.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat5.setProperty("value", 0)
        self.stat5.setObjectName("stat5")
        self.disp5 = QtWidgets.QLCDNumber(self.groupBox_14)
        self.disp5.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp5.setPalette(palette)
        self.disp5.setAutoFillBackground(True)
        self.disp5.setObjectName("disp5")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_12.setGeometry(QtCore.QRect(590, 1010, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.stat6 = QtWidgets.QProgressBar(self.groupBox_12)
        self.stat6.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat6.setProperty("value", 0)
        self.stat6.setObjectName("stat6")
        self.disp6 = QtWidgets.QLCDNumber(self.groupBox_12)
        self.disp6.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp6.setPalette(palette)
        self.disp6.setAutoFillBackground(True)
        self.disp6.setObjectName("disp6")
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_13.setGeometry(QtCore.QRect(590, 1130, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.stat8 = QtWidgets.QProgressBar(self.groupBox_13)
        self.stat8.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat8.setProperty("value", 0)
        self.stat8.setObjectName("stat8")
        self.disp8 = QtWidgets.QLCDNumber(self.groupBox_13)
        self.disp8.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp8.setPalette(palette)
        self.disp8.setAutoFillBackground(True)
        self.disp8.setObjectName("disp8")
        self.time = QtWidgets.QLabel(self.centralWidget)
        self.time.setGeometry(QtCore.QRect(1240, 1060, 311, 91))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(1390, 99, 201, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.disp9 = QtWidgets.QLCDNumber(self.groupBox)
        self.disp9.setGeometry(QtCore.QRect(20, 30, 81, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp9.setPalette(palette)
        self.disp9.setAutoFillBackground(True)
        self.disp9.setObjectName("disp9")
        self.disp10 = QtWidgets.QLCDNumber(self.groupBox)
        self.disp10.setGeometry(QtCore.QRect(20, 110, 81, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp10.setPalette(palette)
        self.disp10.setAutoFillBackground(True)
        self.disp10.setObjectName("disp10")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(120, 50, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(120, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(1390, 310, 201, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.disp11 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.disp11.setGeometry(QtCore.QRect(20, 30, 81, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp11.setPalette(palette)
        self.disp11.setAutoFillBackground(True)
        self.disp11.setObjectName("disp11")
        self.disp12 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.disp12.setGeometry(QtCore.QRect(20, 110, 81, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp12.setPalette(palette)
        self.disp12.setAutoFillBackground(True)
        self.disp12.setObjectName("disp12")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(120, 40, 47, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(120, 130, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gohome = QtWidgets.QLabel(self.centralWidget)
        self.gohome.setGeometry(QtCore.QRect(1180, 1030, 411, 31))
        self.gohome.setText("")
        self.gohome.setObjectName("gohome")
        self.groupBox_16 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_16.setGeometry(QtCore.QRect(10, 1010, 571, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.stat2 = QtWidgets.QProgressBar(self.groupBox_16)
        self.stat2.setGeometry(QtCore.QRect(50, 20, 481, 31))
        self.stat2.setProperty("value", 0)
        self.stat2.setObjectName("stat2")
        self.disp2 = QtWidgets.QLCDNumber(self.groupBox_16)
        self.disp2.setGeometry(QtCore.QRect(490, 20, 51, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.disp2.setPalette(palette)
        self.disp2.setAutoFillBackground(True)
        self.disp2.setObjectName("disp2")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pos1.setItemText(0, _translate("MainWindow", "A"))
        self.pos1.setItemText(1, _translate("MainWindow", "B"))
        self.pal_1.setText(_translate("MainWindow", "Pallet 1"))
        self.label_2.setText(_translate("MainWindow", "  Empty   Prepped    Ω Tested    CO2 End Pieces    Leak Tested      Cut    Length Measured    Silver Epoxied"))
        self.next1.setText(_translate("MainWindow", ">"))
        self.last1.setText(_translate("MainWindow", "<"))
        self.pos2.setItemText(0, _translate("MainWindow", "A"))
        self.pos2.setItemText(1, _translate("MainWindow", "B"))
        self.pal_2.setText(_translate("MainWindow", "Pallet 2"))
        self.pos3.setItemText(0, _translate("MainWindow", "A"))
        self.pos3.setItemText(1, _translate("MainWindow", "B"))
        self.pal_3.setText(_translate("MainWindow", "Pallet 3"))
        self.pos4.setItemText(0, _translate("MainWindow", "A"))
        self.pos4.setItemText(1, _translate("MainWindow", "B"))
        self.pal_4.setText(_translate("MainWindow", "Pallet 4"))
        self.pos5.setItemText(0, _translate("MainWindow", "A"))
        self.pos5.setItemText(1, _translate("MainWindow", "B"))
        self.pal_5.setText(_translate("MainWindow", "Pallet 5"))
        self.pos6.setItemText(0, _translate("MainWindow", "A"))
        self.pos6.setItemText(1, _translate("MainWindow", "B"))
        self.pal_6.setText(_translate("MainWindow", "Pallet 6"))
        self.pos7.setItemText(0, _translate("MainWindow", "A"))
        self.pos7.setItemText(1, _translate("MainWindow", "B"))
        self.pal_7.setText(_translate("MainWindow", "Pallet 7"))
        self.last2.setText(_translate("MainWindow", "<"))
        self.next2.setText(_translate("MainWindow", ">"))
        self.last3.setText(_translate("MainWindow", "<"))
        self.next3.setText(_translate("MainWindow", ">"))
        self.last4.setText(_translate("MainWindow", "<"))
        self.next4.setText(_translate("MainWindow", ">"))
        self.last5.setText(_translate("MainWindow", "<"))
        self.next5.setText(_translate("MainWindow", ">"))
        self.last6.setText(_translate("MainWindow", "<"))
        self.next6.setText(_translate("MainWindow", ">"))
        self.last7.setText(_translate("MainWindow", "<"))
        self.next7.setText(_translate("MainWindow", ">"))
        self.next8.setText(_translate("MainWindow", ">"))
        self.last8.setText(_translate("MainWindow", "<"))
        self.pos8.setItemText(0, _translate("MainWindow", "A"))
        self.pos8.setItemText(1, _translate("MainWindow", "B"))
        self.pal_8.setText(_translate("MainWindow", "Pallet 8"))
        self.next9.setText(_translate("MainWindow", ">"))
        self.last9.setText(_translate("MainWindow", "<"))
        self.pos9.setItemText(0, _translate("MainWindow", "A"))
        self.pos9.setItemText(1, _translate("MainWindow", "B"))
        self.pal_9.setText(_translate("MainWindow", "Pallet 9"))
        self.next10.setText(_translate("MainWindow", ">"))
        self.last10.setText(_translate("MainWindow", "<"))
        self.pos10.setItemText(0, _translate("MainWindow", "A"))
        self.pos10.setItemText(1, _translate("MainWindow", "B"))
        self.pal_10.setText(_translate("MainWindow", "Pallet 10"))
        self.next11.setText(_translate("MainWindow", ">"))
        self.last11.setText(_translate("MainWindow", "<"))
        self.pos11.setItemText(0, _translate("MainWindow", "A"))
        self.pos11.setItemText(1, _translate("MainWindow", "B"))
        self.pal_11.setText(_translate("MainWindow", "Pallet 11"))
        self.next12.setText(_translate("MainWindow", ">"))
        self.last12.setText(_translate("MainWindow", "<"))
        self.pos12.setItemText(0, _translate("MainWindow", "A"))
        self.pos12.setItemText(1, _translate("MainWindow", "B"))
        self.pal_12.setText(_translate("MainWindow", "Pallet 12"))
        self.next20.setText(_translate("MainWindow", ">"))
        self.last20.setText(_translate("MainWindow", "<"))
        self.pos20.setItemText(0, _translate("MainWindow", "A"))
        self.pos20.setItemText(1, _translate("MainWindow", "B"))
        self.pal_20.setText(_translate("MainWindow", "Pallet 20"))
        self.pos17.setItemText(0, _translate("MainWindow", "A"))
        self.pos17.setItemText(1, _translate("MainWindow", "B"))
        self.last17.setText(_translate("MainWindow", "<"))
        self.next17.setText(_translate("MainWindow", ">"))
        self.pal_17.setText(_translate("MainWindow", "Pallet 17"))
        self.next24.setText(_translate("MainWindow", ">"))
        self.last24.setText(_translate("MainWindow", "<"))
        self.pos24.setItemText(0, _translate("MainWindow", "A"))
        self.pos24.setItemText(1, _translate("MainWindow", "B"))
        self.pal_24.setText(_translate("MainWindow", "Pallet 24"))
        self.pos16.setItemText(0, _translate("MainWindow", "A"))
        self.pos16.setItemText(1, _translate("MainWindow", "B"))
        self.last16.setText(_translate("MainWindow", "<"))
        self.next16.setText(_translate("MainWindow", ">"))
        self.pal_16.setText(_translate("MainWindow", "Pallet 16"))
        self.label_23.setText(_translate("MainWindow", "  Empty   Prepped    Ω Tested    CO2 End Pieces    Leak Tested      Cut    Length Measured    Silver Epoxied"))
        self.pos18.setItemText(0, _translate("MainWindow", "A"))
        self.pos18.setItemText(1, _translate("MainWindow", "B"))
        self.last18.setText(_translate("MainWindow", "<"))
        self.next18.setText(_translate("MainWindow", ">"))
        self.pal_18.setText(_translate("MainWindow", "Pallet 18"))
        self.pos19.setItemText(0, _translate("MainWindow", "A"))
        self.pos19.setItemText(1, _translate("MainWindow", "B"))
        self.last19.setText(_translate("MainWindow", "<"))
        self.next19.setText(_translate("MainWindow", ">"))
        self.pal_19.setText(_translate("MainWindow", "Pallet 19"))
        self.pos14.setItemText(0, _translate("MainWindow", "A"))
        self.pos14.setItemText(1, _translate("MainWindow", "B"))
        self.last14.setText(_translate("MainWindow", "<"))
        self.next14.setText(_translate("MainWindow", ">"))
        self.pal_14.setText(_translate("MainWindow", "Pallet 14"))
        self.next23.setText(_translate("MainWindow", ">"))
        self.last23.setText(_translate("MainWindow", "<"))
        self.pos23.setItemText(0, _translate("MainWindow", "A"))
        self.pos23.setItemText(1, _translate("MainWindow", "B"))
        self.pal_23.setText(_translate("MainWindow", "Pallet 23"))
        self.next22.setText(_translate("MainWindow", ">"))
        self.last22.setText(_translate("MainWindow", "<"))
        self.pos22.setItemText(0, _translate("MainWindow", "A"))
        self.pos22.setItemText(1, _translate("MainWindow", "B"))
        self.pal_22.setText(_translate("MainWindow", "Pallet 22"))
        self.pos13.setItemText(0, _translate("MainWindow", "A"))
        self.pos13.setItemText(1, _translate("MainWindow", "B"))
        self.last13.setText(_translate("MainWindow", "<"))
        self.next13.setText(_translate("MainWindow", ">"))
        self.pal_13.setText(_translate("MainWindow", "Pallet 13"))
        self.next21.setText(_translate("MainWindow", ">"))
        self.last21.setText(_translate("MainWindow", "<"))
        self.pos21.setItemText(0, _translate("MainWindow", "A"))
        self.pos21.setItemText(1, _translate("MainWindow", "B"))
        self.pal_21.setText(_translate("MainWindow", "Pallet 21"))
        self.pos15.setItemText(0, _translate("MainWindow", "A"))
        self.pos15.setItemText(1, _translate("MainWindow", "B"))
        self.next15.setText(_translate("MainWindow", ">"))
        self.last15.setText(_translate("MainWindow", "<"))
        self.pal_15.setText(_translate("MainWindow", "Pallet 15"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Lab Status"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Workers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Worker Status"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Empty"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Ω Tested"))
        self.groupBox_15.setTitle(_translate("MainWindow", "CO2 End Pieces"))
        self.groupBox_9.setTitle(_translate("MainWindow", " Length Measured"))
        self.groupBox_14.setTitle(_translate("MainWindow", " Leak Tested"))
        self.groupBox_12.setTitle(_translate("MainWindow", " Cut"))
        self.groupBox_13.setTitle(_translate("MainWindow", " Silver Epoxied"))
        self.time.setText(_translate("MainWindow", ":"))
        self.groupBox.setTitle(_translate("MainWindow", "464 Main"))
        self.label_15.setText(_translate("MainWindow", "℃"))
        self.label_16.setText(_translate("MainWindow", "% H2O"))
        self.groupBox_2.setTitle(_translate("MainWindow", "464B"))
        self.label_17.setText(_translate("MainWindow", "℃"))
        self.label_18.setText(_translate("MainWindow", "% H2O"))
        self.groupBox_16.setTitle(_translate("MainWindow", "Prepped"))

