# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remove.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogBox(object):
    def setupUi(self, DialogBox):
        DialogBox.setObjectName("DialogBox")
        DialogBox.setWindowModality(QtCore.Qt.ApplicationModal)
        DialogBox.resize(761, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogBox.sizePolicy().hasHeightForWidth())
        DialogBox.setSizePolicy(sizePolicy)
        DialogBox.setAutoFillBackground(True)
        DialogBox.setStyleSheet("")
        self.groupBox_2 = QtWidgets.QGroupBox(DialogBox)
        self.groupBox_2.setGeometry(QtCore.QRect(120, 80, 101, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.straw_1 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_1.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_1.setFont(font)
        self.straw_1.setObjectName("straw_1")
        self.straw_2 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_2.setFont(font)
        self.straw_2.setObjectName("straw_2")
        self.straw_3 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_3.setGeometry(QtCore.QRect(10, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_3.setFont(font)
        self.straw_3.setObjectName("straw_3")
        self.straw_4 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_4.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_4.setFont(font)
        self.straw_4.setObjectName("straw_4")
        self.straw_5 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_5.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_5.setFont(font)
        self.straw_5.setObjectName("straw_5")
        self.straw_6 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_6.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_6.setFont(font)
        self.straw_6.setObjectName("straw_6")
        self.straw_7 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_7.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_7.setFont(font)
        self.straw_7.setObjectName("straw_7")
        self.straw_8 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_8.setGeometry(QtCore.QRect(10, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_8.setFont(font)
        self.straw_8.setObjectName("straw_8")
        self.straw_9 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_9.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_9.setFont(font)
        self.straw_9.setObjectName("straw_9")
        self.straw_10 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_10.setGeometry(QtCore.QRect(10, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_10.setFont(font)
        self.straw_10.setObjectName("straw_10")
        self.straw_11 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_11.setGeometry(QtCore.QRect(10, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_11.setFont(font)
        self.straw_11.setObjectName("straw_11")
        self.straw_12 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_12.setGeometry(QtCore.QRect(10, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_12.setFont(font)
        self.straw_12.setObjectName("straw_12")
        self.straw_13 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_13.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_13.setFont(font)
        self.straw_13.setObjectName("straw_13")
        self.straw_14 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_14.setGeometry(QtCore.QRect(10, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_14.setFont(font)
        self.straw_14.setObjectName("straw_14")
        self.straw_15 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_15.setGeometry(QtCore.QRect(10, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_15.setFont(font)
        self.straw_15.setObjectName("straw_15")
        self.straw_16 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_16.setGeometry(QtCore.QRect(10, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_16.setFont(font)
        self.straw_16.setObjectName("straw_16")
        self.straw_17 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_17.setGeometry(QtCore.QRect(10, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_17.setFont(font)
        self.straw_17.setObjectName("straw_17")
        self.straw_18 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_18.setGeometry(QtCore.QRect(10, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_18.setFont(font)
        self.straw_18.setObjectName("straw_18")
        self.straw_19 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_19.setGeometry(QtCore.QRect(10, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_19.setFont(font)
        self.straw_19.setObjectName("straw_19")
        self.straw_20 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_20.setGeometry(QtCore.QRect(10, 590, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_20.setFont(font)
        self.straw_20.setObjectName("straw_20")
        self.straw_21 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_21.setGeometry(QtCore.QRect(10, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_21.setFont(font)
        self.straw_21.setObjectName("straw_21")
        self.straw_22 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_22.setGeometry(QtCore.QRect(10, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_22.setFont(font)
        self.straw_22.setObjectName("straw_22")
        self.straw_23 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_23.setGeometry(QtCore.QRect(10, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_23.setFont(font)
        self.straw_23.setObjectName("straw_23")
        self.straw_24 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_24.setGeometry(QtCore.QRect(10, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_24.setFont(font)
        self.straw_24.setObjectName("straw_24")
        self.groupBox_3 = QtWidgets.QGroupBox(DialogBox)
        self.groupBox_3.setGeometry(QtCore.QRect(230, 80, 101, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pf_1 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_1.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_1.setFont(font)
        self.pf_1.setObjectName("pf_1")
        self.pf_2 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_2.setFont(font)
        self.pf_2.setObjectName("pf_2")
        self.pf_3 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_3.setGeometry(QtCore.QRect(10, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_3.setFont(font)
        self.pf_3.setObjectName("pf_3")
        self.pf_4 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_4.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_4.setFont(font)
        self.pf_4.setObjectName("pf_4")
        self.pf_5 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_5.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_5.setFont(font)
        self.pf_5.setObjectName("pf_5")
        self.pf_6 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_6.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_6.setFont(font)
        self.pf_6.setObjectName("pf_6")
        self.pf_7 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_7.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_7.setFont(font)
        self.pf_7.setObjectName("pf_7")
        self.pf_8 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_8.setGeometry(QtCore.QRect(10, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_8.setFont(font)
        self.pf_8.setObjectName("pf_8")
        self.pf_9 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_9.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_9.setFont(font)
        self.pf_9.setObjectName("pf_9")
        self.pf_10 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_10.setGeometry(QtCore.QRect(10, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_10.setFont(font)
        self.pf_10.setObjectName("pf_10")
        self.pf_11 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_11.setGeometry(QtCore.QRect(10, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_11.setFont(font)
        self.pf_11.setObjectName("pf_11")
        self.pf_12 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_12.setGeometry(QtCore.QRect(10, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_12.setFont(font)
        self.pf_12.setObjectName("pf_12")
        self.pf_13 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_13.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_13.setFont(font)
        self.pf_13.setObjectName("pf_13")
        self.pf_14 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_14.setGeometry(QtCore.QRect(10, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_14.setFont(font)
        self.pf_14.setObjectName("pf_14")
        self.pf_15 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_15.setGeometry(QtCore.QRect(10, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_15.setFont(font)
        self.pf_15.setObjectName("pf_15")
        self.pf_16 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_16.setGeometry(QtCore.QRect(10, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_16.setFont(font)
        self.pf_16.setObjectName("pf_16")
        self.pf_17 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_17.setGeometry(QtCore.QRect(10, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_17.setFont(font)
        self.pf_17.setObjectName("pf_17")
        self.pf_18 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_18.setGeometry(QtCore.QRect(10, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_18.setFont(font)
        self.pf_18.setObjectName("pf_18")
        self.pf_19 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_19.setGeometry(QtCore.QRect(10, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_19.setFont(font)
        self.pf_19.setObjectName("pf_19")
        self.pf_20 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_20.setGeometry(QtCore.QRect(10, 590, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_20.setFont(font)
        self.pf_20.setObjectName("pf_20")
        self.pf_21 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_21.setGeometry(QtCore.QRect(10, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_21.setFont(font)
        self.pf_21.setObjectName("pf_21")
        self.pf_22 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_22.setGeometry(QtCore.QRect(10, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_22.setFont(font)
        self.pf_22.setObjectName("pf_22")
        self.pf_23 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_23.setGeometry(QtCore.QRect(10, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_23.setFont(font)
        self.pf_23.setObjectName("pf_23")
        self.pf_24 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_24.setGeometry(QtCore.QRect(10, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_24.setFont(font)
        self.pf_24.setObjectName("pf_24")
        self.groupBox_4 = QtWidgets.QGroupBox(DialogBox)
        self.groupBox_4.setGeometry(QtCore.QRect(340, 80, 131, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.remove_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_1.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_1.setFont(font)
        self.remove_1.setObjectName("remove_1")
        self.removeButtons = QtWidgets.QButtonGroup(DialogBox)
        self.removeButtons.setObjectName("removeButtons")
        self.removeButtons.addButton(self.remove_1)
        self.remove_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_2.setFont(font)
        self.remove_2.setObjectName("remove_2")
        self.removeButtons.addButton(self.remove_2)
        self.remove_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_3.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_3.setFont(font)
        self.remove_3.setObjectName("remove_3")
        self.removeButtons.addButton(self.remove_3)
        self.remove_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_4.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_4.setFont(font)
        self.remove_4.setObjectName("remove_4")
        self.removeButtons.addButton(self.remove_4)
        self.remove_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_5.setGeometry(QtCore.QRect(10, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_5.setFont(font)
        self.remove_5.setObjectName("remove_5")
        self.removeButtons.addButton(self.remove_5)
        self.remove_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_6.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_6.setFont(font)
        self.remove_6.setObjectName("remove_6")
        self.removeButtons.addButton(self.remove_6)
        self.remove_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_7.setGeometry(QtCore.QRect(10, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_7.setFont(font)
        self.remove_7.setObjectName("remove_7")
        self.removeButtons.addButton(self.remove_7)
        self.remove_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_8.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_8.setFont(font)
        self.remove_8.setObjectName("remove_8")
        self.removeButtons.addButton(self.remove_8)
        self.remove_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_9.setGeometry(QtCore.QRect(10, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_9.setFont(font)
        self.remove_9.setObjectName("remove_9")
        self.removeButtons.addButton(self.remove_9)
        self.remove_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_10.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_10.setFont(font)
        self.remove_10.setObjectName("remove_10")
        self.removeButtons.addButton(self.remove_10)
        self.remove_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_11.setGeometry(QtCore.QRect(10, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_11.setFont(font)
        self.remove_11.setObjectName("remove_11")
        self.removeButtons.addButton(self.remove_11)
        self.remove_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_12.setGeometry(QtCore.QRect(10, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_12.setFont(font)
        self.remove_12.setObjectName("remove_12")
        self.removeButtons.addButton(self.remove_12)
        self.remove_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_13.setGeometry(QtCore.QRect(10, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_13.setFont(font)
        self.remove_13.setObjectName("remove_13")
        self.removeButtons.addButton(self.remove_13)
        self.remove_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_14.setGeometry(QtCore.QRect(10, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_14.setFont(font)
        self.remove_14.setObjectName("remove_14")
        self.removeButtons.addButton(self.remove_14)
        self.remove_15 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_15.setGeometry(QtCore.QRect(10, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_15.setFont(font)
        self.remove_15.setObjectName("remove_15")
        self.removeButtons.addButton(self.remove_15)
        self.remove_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_16.setGeometry(QtCore.QRect(10, 470, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_16.setFont(font)
        self.remove_16.setObjectName("remove_16")
        self.removeButtons.addButton(self.remove_16)
        self.remove_17 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_17.setGeometry(QtCore.QRect(10, 500, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_17.setFont(font)
        self.remove_17.setObjectName("remove_17")
        self.removeButtons.addButton(self.remove_17)
        self.remove_18 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_18.setGeometry(QtCore.QRect(10, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_18.setFont(font)
        self.remove_18.setObjectName("remove_18")
        self.removeButtons.addButton(self.remove_18)
        self.remove_19 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_19.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_19.setFont(font)
        self.remove_19.setObjectName("remove_19")
        self.removeButtons.addButton(self.remove_19)
        self.remove_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_20.setGeometry(QtCore.QRect(10, 590, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_20.setFont(font)
        self.remove_20.setObjectName("remove_20")
        self.removeButtons.addButton(self.remove_20)
        self.remove_21 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_21.setGeometry(QtCore.QRect(10, 620, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_21.setFont(font)
        self.remove_21.setObjectName("remove_21")
        self.removeButtons.addButton(self.remove_21)
        self.remove_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_22.setGeometry(QtCore.QRect(10, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_22.setFont(font)
        self.remove_22.setObjectName("remove_22")
        self.removeButtons.addButton(self.remove_22)
        self.remove_23 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_23.setGeometry(QtCore.QRect(10, 680, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_23.setFont(font)
        self.remove_23.setObjectName("remove_23")
        self.removeButtons.addButton(self.remove_23)
        self.remove_24 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_24.setGeometry(QtCore.QRect(10, 710, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_24.setFont(font)
        self.remove_24.setObjectName("remove_24")
        self.removeButtons.addButton(self.remove_24)
        self.palletLabel = QtWidgets.QLabel(DialogBox)
        self.palletLabel.setGeometry(QtCore.QRect(80, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.palletLabel.setFont(font)
        self.palletLabel.setObjectName("palletLabel")
        self.lastLabel = QtWidgets.QLabel(DialogBox)
        self.lastLabel.setGeometry(QtCore.QRect(80, 40, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lastLabel.setFont(font)
        self.lastLabel.setObjectName("lastLabel")
        self.groupBox_5 = QtWidgets.QGroupBox(DialogBox)
        self.groupBox_5.setGeometry(QtCore.QRect(480, 80, 131, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.move_1 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_1.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_1.setFont(font)
        self.move_1.setObjectName("move_1")
        self.moveButtons = QtWidgets.QButtonGroup(DialogBox)
        self.moveButtons.setObjectName("moveButtons")
        self.moveButtons.addButton(self.move_1)
        self.move_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_2.setFont(font)
        self.move_2.setObjectName("move_2")
        self.moveButtons.addButton(self.move_2)
        self.move_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_3.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_3.setFont(font)
        self.move_3.setObjectName("move_3")
        self.moveButtons.addButton(self.move_3)
        self.move_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_4.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_4.setFont(font)
        self.move_4.setObjectName("move_4")
        self.moveButtons.addButton(self.move_4)
        self.move_5 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_5.setGeometry(QtCore.QRect(10, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_5.setFont(font)
        self.move_5.setObjectName("move_5")
        self.moveButtons.addButton(self.move_5)
        self.move_6 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_6.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_6.setFont(font)
        self.move_6.setObjectName("move_6")
        self.moveButtons.addButton(self.move_6)
        self.move_7 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_7.setGeometry(QtCore.QRect(10, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_7.setFont(font)
        self.move_7.setObjectName("move_7")
        self.moveButtons.addButton(self.move_7)
        self.move_8 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_8.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_8.setFont(font)
        self.move_8.setObjectName("move_8")
        self.moveButtons.addButton(self.move_8)
        self.move_9 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_9.setGeometry(QtCore.QRect(10, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_9.setFont(font)
        self.move_9.setObjectName("move_9")
        self.moveButtons.addButton(self.move_9)
        self.move_10 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_10.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_10.setFont(font)
        self.move_10.setObjectName("move_10")
        self.moveButtons.addButton(self.move_10)
        self.move_11 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_11.setGeometry(QtCore.QRect(10, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_11.setFont(font)
        self.move_11.setObjectName("move_11")
        self.moveButtons.addButton(self.move_11)
        self.move_12 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_12.setGeometry(QtCore.QRect(10, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_12.setFont(font)
        self.move_12.setObjectName("move_12")
        self.moveButtons.addButton(self.move_12)
        self.move_13 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_13.setGeometry(QtCore.QRect(10, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_13.setFont(font)
        self.move_13.setObjectName("move_13")
        self.moveButtons.addButton(self.move_13)
        self.move_14 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_14.setGeometry(QtCore.QRect(10, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_14.setFont(font)
        self.move_14.setObjectName("move_14")
        self.moveButtons.addButton(self.move_14)
        self.move_15 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_15.setGeometry(QtCore.QRect(10, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_15.setFont(font)
        self.move_15.setObjectName("move_15")
        self.moveButtons.addButton(self.move_15)
        self.move_16 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_16.setGeometry(QtCore.QRect(10, 470, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_16.setFont(font)
        self.move_16.setObjectName("move_16")
        self.moveButtons.addButton(self.move_16)
        self.move_17 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_17.setGeometry(QtCore.QRect(10, 500, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_17.setFont(font)
        self.move_17.setObjectName("move_17")
        self.moveButtons.addButton(self.move_17)
        self.move_18 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_18.setGeometry(QtCore.QRect(10, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_18.setFont(font)
        self.move_18.setObjectName("move_18")
        self.moveButtons.addButton(self.move_18)
        self.move_19 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_19.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_19.setFont(font)
        self.move_19.setObjectName("move_19")
        self.moveButtons.addButton(self.move_19)
        self.move_20 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_20.setGeometry(QtCore.QRect(10, 590, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_20.setFont(font)
        self.move_20.setObjectName("move_20")
        self.moveButtons.addButton(self.move_20)
        self.move_21 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_21.setGeometry(QtCore.QRect(10, 620, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_21.setFont(font)
        self.move_21.setObjectName("move_21")
        self.moveButtons.addButton(self.move_21)
        self.move_22 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_22.setGeometry(QtCore.QRect(10, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_22.setFont(font)
        self.move_22.setObjectName("move_22")
        self.moveButtons.addButton(self.move_22)
        self.move_23 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_23.setGeometry(QtCore.QRect(10, 680, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_23.setFont(font)
        self.move_23.setObjectName("move_23")
        self.moveButtons.addButton(self.move_23)
        self.move_24 = QtWidgets.QPushButton(self.groupBox_5)
        self.move_24.setGeometry(QtCore.QRect(10, 710, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.move_24.setFont(font)
        self.move_24.setObjectName("move_24")
        self.moveButtons.addButton(self.move_24)
        self.groupBox_6 = QtWidgets.QGroupBox(DialogBox)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 80, 101, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.straw_25 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_25.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_25.setFont(font)
        self.straw_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_25.setObjectName("straw_25")
        self.straw_26 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_26.setGeometry(QtCore.QRect(10, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_26.setFont(font)
        self.straw_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_26.setObjectName("straw_26")
        self.straw_27 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_27.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_27.setFont(font)
        self.straw_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_27.setObjectName("straw_27")
        self.straw_28 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_28.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_28.setFont(font)
        self.straw_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_28.setObjectName("straw_28")
        self.straw_29 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_29.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_29.setFont(font)
        self.straw_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_29.setObjectName("straw_29")
        self.straw_30 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_30.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_30.setFont(font)
        self.straw_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_30.setObjectName("straw_30")
        self.straw_31 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_31.setGeometry(QtCore.QRect(10, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_31.setFont(font)
        self.straw_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_31.setObjectName("straw_31")
        self.straw_32 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_32.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_32.setFont(font)
        self.straw_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_32.setObjectName("straw_32")
        self.straw_33 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_33.setGeometry(QtCore.QRect(10, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_33.setFont(font)
        self.straw_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_33.setObjectName("straw_33")
        self.straw_34 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_34.setGeometry(QtCore.QRect(10, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_34.setFont(font)
        self.straw_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_34.setObjectName("straw_34")
        self.straw_35 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_35.setGeometry(QtCore.QRect(10, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_35.setFont(font)
        self.straw_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_35.setObjectName("straw_35")
        self.straw_36 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_36.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_36.setFont(font)
        self.straw_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_36.setObjectName("straw_36")
        self.straw_37 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_37.setGeometry(QtCore.QRect(10, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_37.setFont(font)
        self.straw_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_37.setObjectName("straw_37")
        self.straw_38 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_38.setGeometry(QtCore.QRect(10, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_38.setFont(font)
        self.straw_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_38.setObjectName("straw_38")
        self.straw_39 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_39.setGeometry(QtCore.QRect(10, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_39.setFont(font)
        self.straw_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_39.setObjectName("straw_39")
        self.straw_40 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_40.setGeometry(QtCore.QRect(10, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_40.setFont(font)
        self.straw_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_40.setObjectName("straw_40")
        self.straw_41 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_41.setGeometry(QtCore.QRect(10, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_41.setFont(font)
        self.straw_41.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_41.setObjectName("straw_41")
        self.straw_42 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_42.setGeometry(QtCore.QRect(10, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_42.setFont(font)
        self.straw_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_42.setObjectName("straw_42")
        self.straw_43 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_43.setGeometry(QtCore.QRect(10, 590, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_43.setFont(font)
        self.straw_43.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_43.setObjectName("straw_43")
        self.straw_44 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_44.setGeometry(QtCore.QRect(10, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_44.setFont(font)
        self.straw_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_44.setObjectName("straw_44")
        self.straw_45 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_45.setGeometry(QtCore.QRect(10, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_45.setFont(font)
        self.straw_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_45.setObjectName("straw_45")
        self.straw_46 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_46.setGeometry(QtCore.QRect(10, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_46.setFont(font)
        self.straw_46.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_46.setObjectName("straw_46")
        self.straw_47 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_47.setGeometry(QtCore.QRect(10, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_47.setFont(font)
        self.straw_47.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_47.setObjectName("straw_47")
        self.straw_48 = QtWidgets.QLabel(self.groupBox_6)
        self.straw_48.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_48.setFont(font)
        self.straw_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.straw_48.setObjectName("straw_48")
        self.Menu = QtWidgets.QComboBox(DialogBox)
        self.Menu.setGeometry(QtCore.QRect(150, 17, 71, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Menu.sizePolicy().hasHeightForWidth())
        self.Menu.setSizePolicy(sizePolicy)
        self.Menu.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Menu.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.Menu.setObjectName("Menu")
        self.groupBox_7 = QtWidgets.QGroupBox(DialogBox)
        self.groupBox_7.setGeometry(QtCore.QRect(620, 80, 131, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.add_1 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_1.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_1.setFont(font)
        self.add_1.setObjectName("add_1")
        self.addButtons = QtWidgets.QButtonGroup(DialogBox)
        self.addButtons.setObjectName("addButtons")
        self.addButtons.addButton(self.add_1)
        self.add_2 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_2.setFont(font)
        self.add_2.setObjectName("add_2")
        self.addButtons.addButton(self.add_2)
        self.add_3 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_3.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_3.setFont(font)
        self.add_3.setObjectName("add_3")
        self.addButtons.addButton(self.add_3)
        self.add_4 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_4.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_4.setFont(font)
        self.add_4.setObjectName("add_4")
        self.addButtons.addButton(self.add_4)
        self.add_5 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_5.setGeometry(QtCore.QRect(10, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_5.setFont(font)
        self.add_5.setObjectName("add_5")
        self.addButtons.addButton(self.add_5)
        self.add_6 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_6.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_6.setFont(font)
        self.add_6.setObjectName("add_6")
        self.addButtons.addButton(self.add_6)
        self.add_7 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_7.setGeometry(QtCore.QRect(10, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_7.setFont(font)
        self.add_7.setObjectName("add_7")
        self.addButtons.addButton(self.add_7)
        self.add_8 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_8.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_8.setFont(font)
        self.add_8.setObjectName("add_8")
        self.addButtons.addButton(self.add_8)
        self.add_9 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_9.setGeometry(QtCore.QRect(10, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_9.setFont(font)
        self.add_9.setObjectName("add_9")
        self.addButtons.addButton(self.add_9)
        self.add_10 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_10.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_10.setFont(font)
        self.add_10.setObjectName("add_10")
        self.addButtons.addButton(self.add_10)
        self.add_11 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_11.setGeometry(QtCore.QRect(10, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_11.setFont(font)
        self.add_11.setObjectName("add_11")
        self.addButtons.addButton(self.add_11)
        self.add_12 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_12.setGeometry(QtCore.QRect(10, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_12.setFont(font)
        self.add_12.setObjectName("add_12")
        self.addButtons.addButton(self.add_12)
        self.add_13 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_13.setGeometry(QtCore.QRect(10, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_13.setFont(font)
        self.add_13.setObjectName("add_13")
        self.addButtons.addButton(self.add_13)
        self.add_14 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_14.setGeometry(QtCore.QRect(10, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_14.setFont(font)
        self.add_14.setObjectName("add_14")
        self.addButtons.addButton(self.add_14)
        self.add_15 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_15.setGeometry(QtCore.QRect(10, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_15.setFont(font)
        self.add_15.setObjectName("add_15")
        self.addButtons.addButton(self.add_15)
        self.add_16 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_16.setGeometry(QtCore.QRect(10, 470, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_16.setFont(font)
        self.add_16.setObjectName("add_16")
        self.addButtons.addButton(self.add_16)
        self.add_17 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_17.setGeometry(QtCore.QRect(10, 500, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_17.setFont(font)
        self.add_17.setObjectName("add_17")
        self.addButtons.addButton(self.add_17)
        self.add_18 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_18.setGeometry(QtCore.QRect(10, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_18.setFont(font)
        self.add_18.setObjectName("add_18")
        self.addButtons.addButton(self.add_18)
        self.add_19 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_19.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_19.setFont(font)
        self.add_19.setObjectName("add_19")
        self.addButtons.addButton(self.add_19)
        self.add_20 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_20.setGeometry(QtCore.QRect(10, 590, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_20.setFont(font)
        self.add_20.setObjectName("add_20")
        self.addButtons.addButton(self.add_20)
        self.add_21 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_21.setGeometry(QtCore.QRect(10, 620, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_21.setFont(font)
        self.add_21.setObjectName("add_21")
        self.addButtons.addButton(self.add_21)
        self.add_22 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_22.setGeometry(QtCore.QRect(10, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_22.setFont(font)
        self.add_22.setObjectName("add_22")
        self.addButtons.addButton(self.add_22)
        self.add_23 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_23.setGeometry(QtCore.QRect(10, 680, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_23.setFont(font)
        self.add_23.setObjectName("add_23")
        self.addButtons.addButton(self.add_23)
        self.add_24 = QtWidgets.QPushButton(self.groupBox_7)
        self.add_24.setGeometry(QtCore.QRect(10, 710, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_24.setFont(font)
        self.add_24.setObjectName("add_24")
        self.addButtons.addButton(self.add_24)

        self.retranslateUi(DialogBox)
        QtCore.QMetaObject.connectSlotsByName(DialogBox)

    def retranslateUi(self, DialogBox):
        _translate = QtCore.QCoreApplication.translate
        DialogBox.setWindowTitle(_translate("DialogBox", "Dialog"))
        self.groupBox_2.setTitle(_translate("DialogBox", "Straw"))
        self.straw_1.setText(_translate("DialogBox", "Straw"))
        self.straw_2.setText(_translate("DialogBox", "Straw"))
        self.straw_3.setText(_translate("DialogBox", "Straw"))
        self.straw_4.setText(_translate("DialogBox", "Straw"))
        self.straw_5.setText(_translate("DialogBox", "Straw"))
        self.straw_6.setText(_translate("DialogBox", "Straw"))
        self.straw_7.setText(_translate("DialogBox", "Straw"))
        self.straw_8.setText(_translate("DialogBox", "Straw"))
        self.straw_9.setText(_translate("DialogBox", "Straw"))
        self.straw_10.setText(_translate("DialogBox", "Straw"))
        self.straw_11.setText(_translate("DialogBox", "Straw"))
        self.straw_12.setText(_translate("DialogBox", "Straw"))
        self.straw_13.setText(_translate("DialogBox", "Straw"))
        self.straw_14.setText(_translate("DialogBox", "Straw"))
        self.straw_15.setText(_translate("DialogBox", "Straw"))
        self.straw_16.setText(_translate("DialogBox", "Straw"))
        self.straw_17.setText(_translate("DialogBox", "Straw"))
        self.straw_18.setText(_translate("DialogBox", "Straw"))
        self.straw_19.setText(_translate("DialogBox", "Straw"))
        self.straw_20.setText(_translate("DialogBox", "Straw"))
        self.straw_21.setText(_translate("DialogBox", "Straw"))
        self.straw_22.setText(_translate("DialogBox", "Straw"))
        self.straw_23.setText(_translate("DialogBox", "Straw"))
        self.straw_24.setText(_translate("DialogBox", "Straw"))
        self.groupBox_3.setTitle(_translate("DialogBox", "Pass/Fail"))
        self.pf_1.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_2.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_3.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_4.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_5.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_6.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_7.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_8.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_9.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_10.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_11.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_12.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_13.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_14.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_15.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_16.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_17.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_18.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_19.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_20.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_21.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_22.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_23.setText(_translate("DialogBox", "Pass/Fail"))
        self.pf_24.setText(_translate("DialogBox", "Pass/Fail"))
        self.groupBox_4.setTitle(_translate("DialogBox", "Remove Straw"))
        self.remove_1.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_2.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_3.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_4.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_5.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_6.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_7.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_8.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_9.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_10.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_11.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_12.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_13.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_14.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_15.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_16.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_17.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_18.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_19.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_20.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_21.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_22.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_23.setText(_translate("DialogBox", "Remove Straw"))
        self.remove_24.setText(_translate("DialogBox", "Remove Straw"))
        self.palletLabel.setText(_translate("DialogBox", "Pallet:"))
        self.lastLabel.setText(_translate("DialogBox", "Last Step:"))
        self.groupBox_5.setTitle(_translate("DialogBox", "Move Straw"))
        self.move_1.setText(_translate("DialogBox", "Move Straw"))
        self.move_2.setText(_translate("DialogBox", "Move Straw"))
        self.move_3.setText(_translate("DialogBox", "Move Straw"))
        self.move_4.setText(_translate("DialogBox", "Move Straw"))
        self.move_5.setText(_translate("DialogBox", "Move Straw"))
        self.move_6.setText(_translate("DialogBox", "Move Straw"))
        self.move_7.setText(_translate("DialogBox", "Move Straw"))
        self.move_8.setText(_translate("DialogBox", "Move Straw"))
        self.move_9.setText(_translate("DialogBox", "Move Straw"))
        self.move_10.setText(_translate("DialogBox", "Move Straw"))
        self.move_11.setText(_translate("DialogBox", "Move Straw"))
        self.move_12.setText(_translate("DialogBox", "Move Straw"))
        self.move_13.setText(_translate("DialogBox", "Move Straw"))
        self.move_14.setText(_translate("DialogBox", "Move Straw"))
        self.move_15.setText(_translate("DialogBox", "Move Straw"))
        self.move_16.setText(_translate("DialogBox", "Move Straw"))
        self.move_17.setText(_translate("DialogBox", "Move Straw"))
        self.move_18.setText(_translate("DialogBox", "Move Straw"))
        self.move_19.setText(_translate("DialogBox", "Move Straw"))
        self.move_20.setText(_translate("DialogBox", "Move Straw"))
        self.move_21.setText(_translate("DialogBox", "Move Straw"))
        self.move_22.setText(_translate("DialogBox", "Move Straw"))
        self.move_23.setText(_translate("DialogBox", "Move Straw"))
        self.move_24.setText(_translate("DialogBox", "Move Straw"))
        self.groupBox_6.setTitle(_translate("DialogBox", "Position"))
        self.straw_25.setText(_translate("DialogBox", "1:"))
        self.straw_26.setText(_translate("DialogBox", "2:"))
        self.straw_27.setText(_translate("DialogBox", "3:"))
        self.straw_28.setText(_translate("DialogBox", "4:"))
        self.straw_29.setText(_translate("DialogBox", "5:"))
        self.straw_30.setText(_translate("DialogBox", "6:"))
        self.straw_31.setText(_translate("DialogBox", "7:"))
        self.straw_32.setText(_translate("DialogBox", "8:"))
        self.straw_33.setText(_translate("DialogBox", "9:"))
        self.straw_34.setText(_translate("DialogBox", "10:"))
        self.straw_35.setText(_translate("DialogBox", "11:"))
        self.straw_36.setText(_translate("DialogBox", "12:"))
        self.straw_37.setText(_translate("DialogBox", "13:"))
        self.straw_38.setText(_translate("DialogBox", "14:"))
        self.straw_39.setText(_translate("DialogBox", "15:"))
        self.straw_40.setText(_translate("DialogBox", "16:"))
        self.straw_41.setText(_translate("DialogBox", "17:"))
        self.straw_42.setText(_translate("DialogBox", "18:"))
        self.straw_43.setText(_translate("DialogBox", "19:"))
        self.straw_44.setText(_translate("DialogBox", "20:"))
        self.straw_45.setText(_translate("DialogBox", "21:"))
        self.straw_46.setText(_translate("DialogBox", "22:"))
        self.straw_47.setText(_translate("DialogBox", "23:"))
        self.straw_48.setText(_translate("DialogBox", "0:"))
        self.groupBox_7.setTitle(_translate("DialogBox", "Add Straw"))
        self.add_1.setText(_translate("DialogBox", "Add Straw"))
        self.add_2.setText(_translate("DialogBox", "Add Straw"))
        self.add_3.setText(_translate("DialogBox", "Add Straw"))
        self.add_4.setText(_translate("DialogBox", "Add Straw"))
        self.add_5.setText(_translate("DialogBox", "Add Straw"))
        self.add_6.setText(_translate("DialogBox", "Add Straw"))
        self.add_7.setText(_translate("DialogBox", "Add Straw"))
        self.add_8.setText(_translate("DialogBox", "Add Straw"))
        self.add_9.setText(_translate("DialogBox", "Add Straw"))
        self.add_10.setText(_translate("DialogBox", "Add Straw"))
        self.add_11.setText(_translate("DialogBox", "Add Straw"))
        self.add_12.setText(_translate("DialogBox", "Add Straw"))
        self.add_13.setText(_translate("DialogBox", "Add Straw"))
        self.add_14.setText(_translate("DialogBox", "Add Straw"))
        self.add_15.setText(_translate("DialogBox", "Add Straw"))
        self.add_16.setText(_translate("DialogBox", "Add Straw"))
        self.add_17.setText(_translate("DialogBox", "Add Straw"))
        self.add_18.setText(_translate("DialogBox", "Add Straw"))
        self.add_19.setText(_translate("DialogBox", "Add Straw"))
        self.add_20.setText(_translate("DialogBox", "Add Straw"))
        self.add_21.setText(_translate("DialogBox", "Add Straw"))
        self.add_22.setText(_translate("DialogBox", "Add Straw"))
        self.add_23.setText(_translate("DialogBox", "Add Straw"))
        self.add_24.setText(_translate("DialogBox", "Add Straw"))

