# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'channelWidgetUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_form(object):
    def setupUi(self, form):
        form.setObjectName("form")
        form.resize(2000, 500)
        form.setMinimumSize(QtCore.QSize(2000, 500))
        self.gridLayout_4 = QtWidgets.QGridLayout(form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.primaryFrame = QtWidgets.QFrame(form)
        self.primaryFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.primaryFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.primaryFrame.setObjectName("primaryFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.primaryFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.voltageLCDNumber = QtWidgets.QLCDNumber(self.primaryFrame)
        self.voltageLCDNumber.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.voltageLCDNumber.setFont(font)
        self.voltageLCDNumber.setObjectName("voltageLCDNumber")
        self.gridLayout_2.addWidget(self.voltageLCDNumber, 2, 0, 1, 1)
        self.voltageLabel = QtWidgets.QLabel(self.primaryFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.voltageLabel.setFont(font)
        self.voltageLabel.setObjectName("voltageLabel")
        self.gridLayout_2.addWidget(self.voltageLabel, 1, 0, 1, 1)
        self.saveToLabel = QtWidgets.QLabel(self.primaryFrame)
        self.saveToLabel.setObjectName("saveToLabel")
        self.gridLayout_2.addWidget(self.saveToLabel, 3, 0, 1, 1)
        self.channelLabel = QtWidgets.QLabel(self.primaryFrame)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.channelLabel.setFont(font)
        self.channelLabel.setObjectName("channelLabel")
        self.gridLayout_2.addWidget(self.channelLabel, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.graphFrame = QtWidgets.QFrame(self.primaryFrame)
        self.graphFrame.setMinimumSize(QtCore.QSize(600, 200))
        self.graphFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.graphFrame.setObjectName("graphFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.graphFrame)
        self.gridLayout.setObjectName("gridLayout")
        self.graphVerticalLayout = QtWidgets.QVBoxLayout()
        self.graphVerticalLayout.setObjectName("graphVerticalLayout")
        self.gridLayout.addLayout(self.graphVerticalLayout, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.graphFrame, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.primaryFrame, 0, 0, 1, 1)

        self.retranslateUi(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslateUi(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("form", "Form"))
        self.voltageLabel.setText(_translate("form", "Voltage"))
        self.saveToLabel.setText(_translate("form", "Saving to <file location>"))
        self.channelLabel.setText(_translate("form", "Channel X"))
