# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saveDialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saveLocationDialog(object):
    def setupUi(self, saveLocationDialog):
        saveLocationDialog.setObjectName("saveLocationDialog")
        saveLocationDialog.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(saveLocationDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(saveLocationDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.okButton = QtWidgets.QPushButton(saveLocationDialog)
        self.okButton.setObjectName("okButton")
        self.gridLayout.addWidget(self.okButton, 2, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(saveLocationDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 1, 1, 1)
        self.newSaveLocationLE = QtWidgets.QLineEdit(saveLocationDialog)
        self.newSaveLocationLE.setObjectName("newSaveLocationLE")
        self.gridLayout.addWidget(self.newSaveLocationLE, 0, 1, 1, 1)

        self.retranslateUi(saveLocationDialog)
        QtCore.QMetaObject.connectSlotsByName(saveLocationDialog)

    def retranslateUi(self, saveLocationDialog):
        _translate = QtCore.QCoreApplication.translate
        saveLocationDialog.setWindowTitle(_translate("saveLocationDialog", "Dialog"))
        self.label.setText(_translate("saveLocationDialog", "New Save Location"))
        self.okButton.setText(_translate("saveLocationDialog", "OK"))
        self.cancelButton.setText(_translate("saveLocationDialog", "Canel"))
