python -m pip install cycler==0.10.0
python -m pip install kiwisolver==1.1.0
python -m pip install matplotlib==3.1.0
python -m pip install numpy==1.16.4
python -m pip install Pillow==6.0.0
python -m pip install PyAutoGUI==0.9.44
python -m pip install PyGetWindow==0.0.5
python -m pip install PyMsgBox==1.0.6
python -m pip install pyparsing==2.4.0
python -m pip install PyQt5==5.12.2
python -m pip install PyQt5-sip==4.19.17
python -m pip install PyRect==0.1.4
python -m pip install PyScreeze==0.1.21
python -m pip install pyserial==3.4
python -m pip install python-dateutil==2.8.0
python -m pip install PythonQwt==0.5.5
python -m pip install PyTweening==1.0.3
python -m pip install scipy==1.5.1
python -m pip install setuptools==40.8.0
python -m pip install sip==4.19.8
python -m pip install six==1.12.0
python -m pip install SQLAlchemy==1.3.5