# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tensionbox_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(30, 60, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 65, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SpinNiter = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinNiter.setGeometry(QtCore.QRect(30, 280, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SpinNiter.setFont(font)
        self.SpinNiter.setMinimum(3)
        self.SpinNiter.setMaximum(20)
        self.SpinNiter.setObjectName("SpinNiter")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 320, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.SpinNpulses = QtWidgets.QSpinBox(self.centralwidget)
        self.SpinNpulses.setGeometry(QtCore.QRect(30, 320, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.SpinNpulses.setFont(font)
        self.SpinNpulses.setMinimum(3)
        self.SpinNpulses.setObjectName("SpinNpulses")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 280, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.runButton = QtWidgets.QPushButton(self.centralwidget)
        self.runButton.setGeometry(QtCore.QRect(30, 230, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.lengthEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lengthEdit.setGeometry(QtCore.QRect(30, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lengthEdit.setFont(font)
        self.lengthEdit.setObjectName("lengthEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(120, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.freqEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.freqEdit.setGeometry(QtCore.QRect(230, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.freqEdit.setFont(font)
        self.freqEdit.setObjectName("freqEdit")
        self.tensionEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.tensionEdit.setGeometry(QtCore.QRect(230, 60, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tensionEdit.setFont(font)
        self.tensionEdit.setObjectName("tensionEdit")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 20, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 60, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 340, 511, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(230, 100, 291, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.panelID = QtWidgets.QLineEdit(self.centralwidget)
        self.panelID.setGeometry(QtCore.QRect(30, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.panelID.setFont(font)
        self.panelID.setObjectName("panelID")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(120, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(580, 40, 501, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(580, 10, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.runnext = QtWidgets.QPushButton(self.centralwidget)
        self.runnext.setGeometry(QtCore.QRect(30, 180, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.runnext.setFont(font)
        self.runnext.setObjectName("runnext")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 130, 301, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_55 = QtWidgets.QGridLayout()
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.label_39 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_55.addWidget(self.label_39, 0, 1, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.gridLayout_55.addWidget(self.label_40, 0, 2, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.gridLayout_55.addWidget(self.label_37, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_55, 0, 0, 1, 1)
        self.scrollAreaTB = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollAreaTB.setEnabled(True)
        self.scrollAreaTB.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scrollAreaTB.setFont(font)
        self.scrollAreaTB.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollAreaTB.setLineWidth(1)
        self.scrollAreaTB.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaTB.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollAreaTB.setWidgetResizable(True)
        self.scrollAreaTB.setObjectName("scrollAreaTB")
        self.scrollContents = QtWidgets.QWidget()
        self.scrollContents.setGeometry(QtCore.QRect(0, 0, 280, 180))
        self.scrollContents.setObjectName("scrollContents")
        self.scrollAreaTB.setWidget(self.scrollContents)
        self.gridLayout_2.addWidget(self.scrollAreaTB, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Straw Number"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Wire"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Straw"))
        self.label_2.setText(_translate("MainWindow", "Measurement Type"))
        self.label_3.setText(_translate("MainWindow", "Number of Pulses"))
        self.label_4.setText(_translate("MainWindow", "Number of Iterations"))
        self.runButton.setText(_translate("MainWindow", "Measure Current"))
        self.label_5.setText(_translate("MainWindow", "Length [m]"))
        self.label_6.setText(_translate("MainWindow", "Frequency [Hz]"))
        self.label_7.setText(_translate("MainWindow", "Tension [g]"))
        self.panelID.setPlaceholderText(_translate("MainWindow", "MN000"))
        self.label_8.setText(_translate("MainWindow", "Panel ID"))
        self.label_9.setText(_translate("MainWindow", "Wire Tension vs. Wire Number"))
        self.runnext.setText(_translate("MainWindow", "Measure Next"))
        self.label_39.setText(_translate("MainWindow", "Wire (g)"))
        self.label_40.setText(_translate("MainWindow", "Straw (g)"))
        self.label_37.setText(_translate("MainWindow", "Number"))


