# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facileDB.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.panelLE = QtWidgets.QLineEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panelLE.sizePolicy().hasHeightForWidth())
        self.panelLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.panelLE.setFont(font)
        self.panelLE.setObjectName("panelLE")
        self.submitPB = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitPB.sizePolicy().hasHeightForWidth())
        self.submitPB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.submitPB.setFont(font)
        self.submitPB.setObjectName("submitPB")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_15.addWidget(self.splitter, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(
            28, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_15.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            1438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.gridLayout_15.addItem(spacerItem1, 0, 3, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.measurementsBox = QtWidgets.QGroupBox(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.measurementsBox.setFont(font)
        self.measurementsBox.setObjectName("measurementsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.measurementsBox)
        self.gridLayout.setObjectName("gridLayout")
        self.hvCurrentBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.hvCurrentBox.setMinimumSize(QtCore.QSize(150, 0))
        self.hvCurrentBox.setObjectName("hvCurrentBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.hvCurrentBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hvExportButton = QtWidgets.QPushButton(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.hvExportButton.setFont(font)
        self.hvExportButton.setObjectName("hvExportButton")
        self.gridLayout_3.addWidget(self.hvExportButton, 2, 0, 1, 1)
        self.hvListWidget = QtWidgets.QListWidget(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hvListWidget.setFont(font)
        self.hvListWidget.setObjectName("hvListWidget")
        self.gridLayout_3.addWidget(self.hvListWidget, 0, 0, 1, 2)
        self.plotHVDataButton = QtWidgets.QPushButton(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plotHVDataButton.setFont(font)
        self.plotHVDataButton.setObjectName("plotHVDataButton")
        self.gridLayout_3.addWidget(self.plotHVDataButton, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.hvCurrentBox, 0, 0, 1, 1)
        self.strawTensionBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.strawTensionBox.setObjectName("strawTensionBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.strawTensionBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.strawListWidget = QtWidgets.QListWidget(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.strawListWidget.setFont(font)
        self.strawListWidget.setObjectName("strawListWidget")
        self.gridLayout_12.addWidget(self.strawListWidget, 0, 0, 1, 2)
        self.strawExportButton = QtWidgets.QPushButton(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.strawExportButton.setFont(font)
        self.strawExportButton.setObjectName("strawExportButton")
        self.gridLayout_12.addWidget(self.strawExportButton, 1, 0, 1, 1)
        self.plotStrawDataButton = QtWidgets.QPushButton(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plotStrawDataButton.setFont(font)
        self.plotStrawDataButton.setObjectName("plotStrawDataButton")
        self.gridLayout_12.addWidget(self.plotStrawDataButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.strawTensionBox, 0, 1, 1, 1)
        self.wireTensionBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.wireTensionBox.setObjectName("wireTensionBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.wireTensionBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.wireListWidget = QtWidgets.QListWidget(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wireListWidget.setFont(font)
        self.wireListWidget.setObjectName("wireListWidget")
        self.gridLayout_13.addWidget(self.wireListWidget, 0, 0, 1, 2)
        self.wireExportButton = QtWidgets.QPushButton(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wireExportButton.setFont(font)
        self.wireExportButton.setObjectName("wireExportButton")
        self.gridLayout_13.addWidget(self.wireExportButton, 1, 0, 1, 1)
        self.plotWireDataButton = QtWidgets.QPushButton(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.plotWireDataButton.setFont(font)
        self.plotWireDataButton.setObjectName("plotWireDataButton")
        self.gridLayout_13.addWidget(self.plotWireDataButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.wireTensionBox, 0, 2, 1, 1)
        self.commentBox = QtWidgets.QGroupBox(self.splitter_3)
        self.commentBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.commentBox.setFont(font)
        self.commentBox.setObjectName("commentBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.commentBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.commentBox)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(730, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.ringsTab = QtWidgets.QWidget()
        self.ringsTab.setObjectName("ringsTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ringsTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ringsComList = QtWidgets.QListWidget(self.ringsTab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringsComList.sizePolicy().hasHeightForWidth())
        self.ringsComList.setSizePolicy(sizePolicy)
        self.ringsComList.setMinimumSize(QtCore.QSize(0, 0))
        self.ringsComList.setObjectName("ringsComList")
        self.gridLayout_5.addWidget(self.ringsComList, 0, 2, 1, 1)
        self.tabWidget.addTab(self.ringsTab, "")
        self.strawsTab = QtWidgets.QWidget()
        self.strawsTab.setObjectName("strawsTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.strawsTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.strawsComList = QtWidgets.QListWidget(self.strawsTab)
        self.strawsComList.setObjectName("strawsComList")
        self.gridLayout_6.addWidget(self.strawsComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.strawsTab, "")
        self.senseWireTab = QtWidgets.QWidget()
        self.senseWireTab.setObjectName("senseWireTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.senseWireTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.senseComList = QtWidgets.QListWidget(self.senseWireTab)
        self.senseComList.setObjectName("senseComList")
        self.gridLayout_7.addWidget(self.senseComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.senseWireTab, "")
        self.pinsTab = QtWidgets.QWidget()
        self.pinsTab.setObjectName("pinsTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pinsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pinsComList = QtWidgets.QListWidget(self.pinsTab)
        self.pinsComList.setObjectName("pinsComList")
        self.gridLayout_8.addWidget(self.pinsComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pinsTab, "")
        self.highVoltageTab = QtWidgets.QWidget()
        self.highVoltageTab.setObjectName("highVoltageTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.highVoltageTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.highComList = QtWidgets.QListWidget(self.highVoltageTab)
        self.highComList.setObjectName("highComList")
        self.gridLayout_9.addWidget(self.highComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.highVoltageTab, "")
        self.manifoldTab = QtWidgets.QWidget()
        self.manifoldTab.setObjectName("manifoldTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.manifoldTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.manifoldComList = QtWidgets.QListWidget(self.manifoldTab)
        self.manifoldComList.setObjectName("manifoldComList")
        self.gridLayout_10.addWidget(self.manifoldComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.manifoldTab, "")
        self.floodingTab = QtWidgets.QWidget()
        self.floodingTab.setObjectName("floodingTab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.floodingTab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.floodingComList = QtWidgets.QListWidget(self.floodingTab)
        self.floodingComList.setObjectName("floodingComList")
        self.gridLayout_11.addWidget(self.floodingComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.floodingTab, "")
        self.finalQCTab = QtWidgets.QWidget()
        self.finalQCTab.setObjectName("finalQCTab")
        self.tabWidget.addTab(self.finalQCTab, "")
        self.storageTab = QtWidgets.QWidget()
        self.storageTab.setObjectName("storageTab")
        self.tabWidget.addTab(self.storageTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.splitter_3, 1, 1, 1, 3)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.paasBox = QtWidgets.QGroupBox(self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.paasBox.setFont(font)
        self.paasBox.setObjectName("paasBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.paasBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_14 = QtWidgets.QLabel(self.paasBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_14.addWidget(self.label_14, 0, 0, 1, 1)
        self.paasAMaxTempLE = QtWidgets.QLineEdit(self.paasBox)
        self.paasAMaxTempLE.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.paasAMaxTempLE.setFont(font)
        self.paasAMaxTempLE.setReadOnly(True)
        self.paasAMaxTempLE.setObjectName("paasAMaxTempLE")
        self.gridLayout_14.addWidget(self.paasAMaxTempLE, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.paasBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_14.addWidget(self.label_15, 2, 0, 1, 1)
        self.paasCMaxTempLE = QtWidgets.QLineEdit(self.paasBox)
        self.paasCMaxTempLE.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.paasCMaxTempLE.setFont(font)
        self.paasCMaxTempLE.setReadOnly(True)
        self.paasCMaxTempLE.setObjectName("paasCMaxTempLE")
        self.gridLayout_14.addWidget(self.paasCMaxTempLE, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.paasBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_14.addWidget(self.label_16, 4, 0, 1, 1)
        self.totalHeatingLE = QtWidgets.QLineEdit(self.paasBox)
        self.totalHeatingLE.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.totalHeatingLE.setFont(font)
        self.totalHeatingLE.setReadOnly(True)
        self.totalHeatingLE.setObjectName("totalHeatingLE")
        self.gridLayout_14.addWidget(self.totalHeatingLE, 5, 0, 1, 1)
        self.ringsSetupBox = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.ringsSetupBox.sizePolicy().hasHeightForWidth()
        )
        self.ringsSetupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ringsSetupBox.setFont(font)
        self.ringsSetupBox.setObjectName("ringsSetupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ringsSetupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ringsMIRLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsMIRLE.setFont(font)
        self.ringsMIRLE.setReadOnly(True)
        self.ringsMIRLE.setObjectName("ringsMIRLE")
        self.gridLayout_4.addWidget(self.ringsMIRLE, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 8, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 9, 0, 1, 1)
        self.ringsPRCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsPRCLE.setFont(font)
        self.ringsPRCLE.setReadOnly(True)
        self.ringsPRCLE.setObjectName("ringsPRCLE")
        self.gridLayout_4.addWidget(self.ringsPRCLE, 8, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 5, 0, 1, 1)
        self.ringsPLCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsPLCLE.setFont(font)
        self.ringsPLCLE.setReadOnly(True)
        self.ringsPLCLE.setObjectName("ringsPLCLE")
        self.gridLayout_4.addWidget(self.ringsPLCLE, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.ringsBIRLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsBIRLE.setFont(font)
        self.ringsBIRLE.setReadOnly(True)
        self.ringsBIRLE.setObjectName("ringsBIRLE")
        self.gridLayout_4.addWidget(self.ringsBIRLE, 2, 1, 1, 1)
        self.ringsPLALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsPLALE.setFont(font)
        self.ringsPLALE.setReadOnly(True)
        self.ringsPLALE.setObjectName("ringsPLALE")
        self.gridLayout_4.addWidget(self.ringsPLALE, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.ringsBasePlateLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsBasePlateLE.setFont(font)
        self.ringsBasePlateLE.setReadOnly(True)
        self.ringsBasePlateLE.setObjectName("ringsBasePlateLE")
        self.gridLayout_4.addWidget(self.ringsBasePlateLE, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 4, 0, 1, 1)
        self.ringsPLBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsPLBLE.setFont(font)
        self.ringsPLBLE.setReadOnly(True)
        self.ringsPLBLE.setObjectName("ringsPLBLE")
        self.gridLayout_4.addWidget(self.ringsPLBLE, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 6, 0, 1, 1)
        self.ringsPRALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsPRALE.setFont(font)
        self.ringsPRALE.setReadOnly(True)
        self.ringsPRALE.setObjectName("ringsPRALE")
        self.gridLayout_4.addWidget(self.ringsPRALE, 6, 1, 1, 1)
        self.ringsPRBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsPRBLE.setFont(font)
        self.ringsPRBLE.setReadOnly(True)
        self.ringsPRBLE.setObjectName("ringsPRBLE")
        self.gridLayout_4.addWidget(self.ringsPRBLE, 7, 1, 1, 1)
        self.ringsALF1LE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsALF1LE.setFont(font)
        self.ringsALF1LE.setReadOnly(True)
        self.ringsALF1LE.setObjectName("ringsALF1LE")
        self.gridLayout_4.addWidget(self.ringsALF1LE, 9, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 10, 0, 1, 1)
        self.ringsALF2LE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.ringsALF2LE.setFont(font)
        self.ringsALF2LE.setReadOnly(True)
        self.ringsALF2LE.setObjectName("ringsALF2LE")
        self.gridLayout_4.addWidget(self.ringsALF2LE, 10, 1, 1, 1)
        self.gridLayout_15.addWidget(self.splitter_2, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Panel ID"))
        self.submitPB.setText(_translate("MainWindow", "Submit"))
        self.label_2.setText(_translate("MainWindow", "MN___"))
        self.measurementsBox.setTitle(_translate("MainWindow", "Measurements"))
        self.hvCurrentBox.setTitle(_translate("MainWindow", "HV Current Data"))
        self.hvExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotHVDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.strawTensionBox.setTitle(_translate("MainWindow", "Straw Tension Data"))
        self.strawExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotStrawDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.wireTensionBox.setTitle(_translate("MainWindow", "Wire Tension Data"))
        self.wireExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotWireDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.commentBox.setTitle(_translate("MainWindow", "Comments"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.ringsTab), _translate("MainWindow", "1 - Rings")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.strawsTab),
            _translate("MainWindow", "2 - Straws"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.senseWireTab),
            _translate("MainWindow", "3 - Sense Wire"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.pinsTab),
            _translate("MainWindow", "4 - Pin Protectors"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.highVoltageTab),
            _translate("MainWindow", "5 - HV"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.manifoldTab),
            _translate("MainWindow", "6 - Manifold"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.floodingTab),
            _translate("MainWindow", "7 - Flooding"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.finalQCTab),
            _translate("MainWindow", "8 - Final QC"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.storageTab),
            _translate("MainWindow", "9 - Storage"),
        )
        self.paasBox.setTitle(_translate("MainWindow", "PAAS Heating Data"))
        self.label_14.setText(_translate("MainWindow", "PAAS A Max Temp"))
        self.label_15.setText(_translate("MainWindow", "PAAS C Max Temp"))
        self.label_16.setText(_translate("MainWindow", "Total Heating Time"))
        self.ringsSetupBox.setTitle(_translate("MainWindow", "Part IDs"))
        self.label_10.setText(_translate("MainWindow", "PIR RB"))
        self.label_11.setText(_translate("MainWindow", "PIR RC"))
        self.label_12.setText(_translate("MainWindow", "ALF 1"))
        self.label_8.setText(_translate("MainWindow", "PIR LC"))
        self.label_5.setText(_translate("MainWindow", "BIR"))
        self.label_3.setText(_translate("MainWindow", "Base Plate"))
        self.label_6.setText(_translate("MainWindow", "PIR LA"))
        self.label_4.setText(_translate("MainWindow", "MIR"))
        self.label_7.setText(_translate("MainWindow", "PIR LB"))
        self.label_9.setText(_translate("MainWindow", "PIR RA"))
        self.label_13.setText(_translate("MainWindow", "ALF 2"))
