# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facileDB.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 871)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.panelLE = QtWidgets.QLineEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panelLE.sizePolicy().hasHeightForWidth())
        self.panelLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.panelLE.setFont(font)
        self.panelLE.setMaxLength(3)
        self.panelLE.setObjectName("panelLE")
        self.submitPB = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitPB.sizePolicy().hasHeightForWidth())
        self.submitPB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.submitPB.setFont(font)
        self.submitPB.setObjectName("submitPB")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_15.addWidget(self.splitter, 0, 0, 1, 2)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.ringsSetupBox = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringsSetupBox.sizePolicy().hasHeightForWidth())
        self.ringsSetupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ringsSetupBox.setFont(font)
        self.ringsSetupBox.setObjectName("ringsSetupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ringsSetupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.partPaasALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPaasALE.setFont(font)
        self.partPaasALE.setReadOnly(True)
        self.partPaasALE.setObjectName("partPaasALE")
        self.gridLayout_4.addWidget(self.partPaasALE, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.partPaasBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPaasBLE.setFont(font)
        self.partPaasBLE.setReadOnly(True)
        self.partPaasBLE.setObjectName("partPaasBLE")
        self.gridLayout_4.addWidget(self.partPaasBLE, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)
        self.partPaasCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPaasCLE.setFont(font)
        self.partPaasCLE.setReadOnly(True)
        self.partPaasCLE.setObjectName("partPaasCLE")
        self.gridLayout_4.addWidget(self.partPaasCLE, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.partBasePlateLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partBasePlateLE.setFont(font)
        self.partBasePlateLE.setReadOnly(True)
        self.partBasePlateLE.setObjectName("partBasePlateLE")
        self.gridLayout_4.addWidget(self.partBasePlateLE, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 0, 1, 1)
        self.partMIRLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partMIRLE.setFont(font)
        self.partMIRLE.setReadOnly(True)
        self.partMIRLE.setObjectName("partMIRLE")
        self.gridLayout_4.addWidget(self.partMIRLE, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 0, 1, 1)
        self.partBIRLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partBIRLE.setFont(font)
        self.partBIRLE.setReadOnly(True)
        self.partBIRLE.setObjectName("partBIRLE")
        self.gridLayout_4.addWidget(self.partBIRLE, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 1)
        self.partPLALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPLALE.setFont(font)
        self.partPLALE.setReadOnly(True)
        self.partPLALE.setObjectName("partPLALE")
        self.gridLayout_4.addWidget(self.partPLALE, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 7, 0, 1, 1)
        self.partPLBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPLBLE.setFont(font)
        self.partPLBLE.setReadOnly(True)
        self.partPLBLE.setObjectName("partPLBLE")
        self.gridLayout_4.addWidget(self.partPLBLE, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 8, 0, 1, 1)
        self.partPLCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPLCLE.setFont(font)
        self.partPLCLE.setReadOnly(True)
        self.partPLCLE.setObjectName("partPLCLE")
        self.gridLayout_4.addWidget(self.partPLCLE, 8, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 9, 0, 1, 1)
        self.partPRALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPRALE.setFont(font)
        self.partPRALE.setReadOnly(True)
        self.partPRALE.setObjectName("partPRALE")
        self.gridLayout_4.addWidget(self.partPRALE, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 10, 0, 1, 1)
        self.partPRBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPRBLE.setFont(font)
        self.partPRBLE.setReadOnly(True)
        self.partPRBLE.setObjectName("partPRBLE")
        self.gridLayout_4.addWidget(self.partPRBLE, 10, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 11, 0, 1, 1)
        self.partPRCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPRCLE.setFont(font)
        self.partPRCLE.setReadOnly(True)
        self.partPRCLE.setObjectName("partPRCLE")
        self.gridLayout_4.addWidget(self.partPRCLE, 11, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 12, 0, 1, 1)
        self.partALF1LE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partALF1LE.setFont(font)
        self.partALF1LE.setReadOnly(True)
        self.partALF1LE.setObjectName("partALF1LE")
        self.gridLayout_4.addWidget(self.partALF1LE, 12, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 13, 0, 1, 1)
        self.partALF2LE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partALF2LE.setFont(font)
        self.partALF2LE.setReadOnly(True)
        self.partALF2LE.setObjectName("partALF2LE")
        self.gridLayout_4.addWidget(self.partALF2LE, 13, 1, 1, 1)
        self.gridLayout_15.addWidget(self.splitter_2, 1, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.measurementsBox = QtWidgets.QGroupBox(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.measurementsBox.setFont(font)
        self.measurementsBox.setObjectName("measurementsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.measurementsBox)
        self.gridLayout.setObjectName("gridLayout")
        self.wireTensionBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.wireTensionBox.setObjectName("wireTensionBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.wireTensionBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.wireListWidget = QtWidgets.QListWidget(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wireListWidget.setFont(font)
        self.wireListWidget.setObjectName("wireListWidget")
        self.gridLayout_13.addWidget(self.wireListWidget, 0, 0, 1, 2)
        self.wireExportButton = QtWidgets.QPushButton(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.wireExportButton.setFont(font)
        self.wireExportButton.setObjectName("wireExportButton")
        self.gridLayout_13.addWidget(self.wireExportButton, 1, 0, 1, 1)
        self.plotWireDataButton = QtWidgets.QPushButton(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotWireDataButton.setFont(font)
        self.plotWireDataButton.setObjectName("plotWireDataButton")
        self.gridLayout_13.addWidget(self.plotWireDataButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.wireTensionBox, 0, 3, 1, 1)
        self.hvCurrentBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.hvCurrentBox.setMinimumSize(QtCore.QSize(150, 0))
        self.hvCurrentBox.setObjectName("hvCurrentBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.hvCurrentBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hvExportButton = QtWidgets.QPushButton(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.hvExportButton.setFont(font)
        self.hvExportButton.setObjectName("hvExportButton")
        self.gridLayout_3.addWidget(self.hvExportButton, 2, 0, 1, 1)
        self.hvListWidget = QtWidgets.QListWidget(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hvListWidget.setFont(font)
        self.hvListWidget.setObjectName("hvListWidget")
        self.gridLayout_3.addWidget(self.hvListWidget, 0, 0, 1, 2)
        self.plotHVDataButton = QtWidgets.QPushButton(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotHVDataButton.setFont(font)
        self.plotHVDataButton.setObjectName("plotHVDataButton")
        self.gridLayout_3.addWidget(self.plotHVDataButton, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.hvCurrentBox, 0, 1, 1, 1)
        self.strawTensionBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.strawTensionBox.setObjectName("strawTensionBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.strawTensionBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.strawListWidget = QtWidgets.QListWidget(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.strawListWidget.setFont(font)
        self.strawListWidget.setObjectName("strawListWidget")
        self.gridLayout_12.addWidget(self.strawListWidget, 0, 0, 1, 2)
        self.strawExportButton = QtWidgets.QPushButton(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.strawExportButton.setFont(font)
        self.strawExportButton.setObjectName("strawExportButton")
        self.gridLayout_12.addWidget(self.strawExportButton, 1, 0, 1, 1)
        self.plotStrawDataButton = QtWidgets.QPushButton(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotStrawDataButton.setFont(font)
        self.plotStrawDataButton.setObjectName("plotStrawDataButton")
        self.gridLayout_12.addWidget(self.plotStrawDataButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.strawTensionBox, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.heatProBox = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.heatProBox.setFont(font)
        self.heatProBox.setObjectName("heatProBox")
        self.heatProBox.addItem("")
        self.heatProBox.addItem("")
        self.heatProBox.addItem("")
        self.gridLayout_14.addWidget(self.heatProBox, 0, 0, 1, 2)
        self.plotHeatDataButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotHeatDataButton.setFont(font)
        self.plotHeatDataButton.setObjectName("plotHeatDataButton")
        self.gridLayout_14.addWidget(self.plotHeatDataButton, 2, 1, 1, 1)
        self.heatExportButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.heatExportButton.setFont(font)
        self.heatExportButton.setObjectName("heatExportButton")
        self.gridLayout_14.addWidget(self.heatExportButton, 2, 0, 1, 1)
        self.heatListWidget = QtWidgets.QListWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.heatListWidget.setFont(font)
        self.heatListWidget.setObjectName("heatListWidget")
        self.gridLayout_14.addWidget(self.heatListWidget, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.commentBox = QtWidgets.QGroupBox(self.splitter_3)
        self.commentBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.commentBox.setFont(font)
        self.commentBox.setObjectName("commentBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.commentBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.commentBox)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(730, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.ringsTab = QtWidgets.QWidget()
        self.ringsTab.setObjectName("ringsTab")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.ringsTab)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.ringsComList = QtWidgets.QListWidget(self.ringsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringsComList.sizePolicy().hasHeightForWidth())
        self.ringsComList.setSizePolicy(sizePolicy)
        self.ringsComList.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ringsComList.setFont(font)
        self.ringsComList.setObjectName("ringsComList")
        self.gridLayout_16.addWidget(self.ringsComList, 0, 0, 2, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_14 = QtWidgets.QLabel(self.ringsTab)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 0, 0, 1, 1)
        self.pro1STime = QtWidgets.QLineEdit(self.ringsTab)
        self.pro1STime.setObjectName("pro1STime")
        self.gridLayout_5.addWidget(self.pro1STime, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.ringsTab)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 1, 0, 1, 1)
        self.pro1ETime = QtWidgets.QLineEdit(self.ringsTab)
        self.pro1ETime.setObjectName("pro1ETime")
        self.gridLayout_5.addWidget(self.pro1ETime, 1, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.ringsTab)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 2, 0, 1, 1)
        self.pro1TTime = QtWidgets.QLineEdit(self.ringsTab)
        self.pro1TTime.setObjectName("pro1TTime")
        self.gridLayout_5.addWidget(self.pro1TTime, 2, 1, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.ringsSesList = QtWidgets.QListWidget(self.ringsTab)
        self.ringsSesList.setObjectName("ringsSesList")
        self.gridLayout_16.addWidget(self.ringsSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.ringsTab, "")
        self.strawsTab = QtWidgets.QWidget()
        self.strawsTab.setObjectName("strawsTab")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.strawsTab)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.strawsComList = QtWidgets.QListWidget(self.strawsTab)
        self.strawsComList.setObjectName("strawsComList")
        self.gridLayout_17.addWidget(self.strawsComList, 0, 0, 2, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_22 = QtWidgets.QLabel(self.strawsTab)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.pro2STime = QtWidgets.QLineEdit(self.strawsTab)
        self.pro2STime.setObjectName("pro2STime")
        self.gridLayout_6.addWidget(self.pro2STime, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.strawsTab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 1, 0, 1, 1)
        self.pro2ETime = QtWidgets.QLineEdit(self.strawsTab)
        self.pro2ETime.setObjectName("pro2ETime")
        self.gridLayout_6.addWidget(self.pro2ETime, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.strawsTab)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 2, 0, 1, 1)
        self.pro2TTime = QtWidgets.QLineEdit(self.strawsTab)
        self.pro2TTime.setObjectName("pro2TTime")
        self.gridLayout_6.addWidget(self.pro2TTime, 2, 1, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_6, 0, 1, 1, 1)
        self.strawsSesList = QtWidgets.QListWidget(self.strawsTab)
        self.strawsSesList.setObjectName("strawsSesList")
        self.gridLayout_17.addWidget(self.strawsSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.strawsTab, "")
        self.senseWireTab = QtWidgets.QWidget()
        self.senseWireTab.setObjectName("senseWireTab")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.senseWireTab)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.senseComList = QtWidgets.QListWidget(self.senseWireTab)
        self.senseComList.setObjectName("senseComList")
        self.gridLayout_18.addWidget(self.senseComList, 0, 0, 2, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtWidgets.QLabel(self.senseWireTab)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 0, 0, 1, 1)
        self.pro3STime = QtWidgets.QLineEdit(self.senseWireTab)
        self.pro3STime.setObjectName("pro3STime")
        self.gridLayout_7.addWidget(self.pro3STime, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.senseWireTab)
        self.label_23.setObjectName("label_23")
        self.gridLayout_7.addWidget(self.label_23, 1, 0, 1, 1)
        self.pro3ETime = QtWidgets.QLineEdit(self.senseWireTab)
        self.pro3ETime.setObjectName("pro3ETime")
        self.gridLayout_7.addWidget(self.pro3ETime, 1, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.senseWireTab)
        self.label_24.setObjectName("label_24")
        self.gridLayout_7.addWidget(self.label_24, 2, 0, 1, 1)
        self.pro3TTime = QtWidgets.QLineEdit(self.senseWireTab)
        self.pro3TTime.setObjectName("pro3TTime")
        self.gridLayout_7.addWidget(self.pro3TTime, 2, 1, 1, 1)
        self.gridLayout_18.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.senseSesList = QtWidgets.QListWidget(self.senseWireTab)
        self.senseSesList.setObjectName("senseSesList")
        self.gridLayout_18.addWidget(self.senseSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.senseWireTab, "")
        self.pinsTab = QtWidgets.QWidget()
        self.pinsTab.setObjectName("pinsTab")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.pinsTab)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pinsComList = QtWidgets.QListWidget(self.pinsTab)
        self.pinsComList.setObjectName("pinsComList")
        self.gridLayout_19.addWidget(self.pinsComList, 0, 0, 2, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_28 = QtWidgets.QLabel(self.pinsTab)
        self.label_28.setObjectName("label_28")
        self.gridLayout_8.addWidget(self.label_28, 0, 0, 1, 1)
        self.pro4STime = QtWidgets.QLineEdit(self.pinsTab)
        self.pro4STime.setObjectName("pro4STime")
        self.gridLayout_8.addWidget(self.pro4STime, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.pinsTab)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 1, 0, 1, 1)
        self.pro4ETime = QtWidgets.QLineEdit(self.pinsTab)
        self.pro4ETime.setObjectName("pro4ETime")
        self.gridLayout_8.addWidget(self.pro4ETime, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.pinsTab)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 2, 0, 1, 1)
        self.pro4TTime = QtWidgets.QLineEdit(self.pinsTab)
        self.pro4TTime.setObjectName("pro4TTime")
        self.gridLayout_8.addWidget(self.pro4TTime, 2, 1, 1, 1)
        self.gridLayout_19.addLayout(self.gridLayout_8, 0, 1, 1, 1)
        self.pinsSesList = QtWidgets.QListWidget(self.pinsTab)
        self.pinsSesList.setObjectName("pinsSesList")
        self.gridLayout_19.addWidget(self.pinsSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.pinsTab, "")
        self.highVoltageTab = QtWidgets.QWidget()
        self.highVoltageTab.setObjectName("highVoltageTab")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.highVoltageTab)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.highComList = QtWidgets.QListWidget(self.highVoltageTab)
        self.highComList.setObjectName("highComList")
        self.gridLayout_20.addWidget(self.highComList, 0, 0, 2, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_30 = QtWidgets.QLabel(self.highVoltageTab)
        self.label_30.setObjectName("label_30")
        self.gridLayout_9.addWidget(self.label_30, 0, 0, 1, 1)
        self.pro5STime = QtWidgets.QLineEdit(self.highVoltageTab)
        self.pro5STime.setObjectName("pro5STime")
        self.gridLayout_9.addWidget(self.pro5STime, 0, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.highVoltageTab)
        self.label_31.setObjectName("label_31")
        self.gridLayout_9.addWidget(self.label_31, 1, 0, 1, 1)
        self.pro5ETime = QtWidgets.QLineEdit(self.highVoltageTab)
        self.pro5ETime.setObjectName("pro5ETime")
        self.gridLayout_9.addWidget(self.pro5ETime, 1, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.highVoltageTab)
        self.label_29.setObjectName("label_29")
        self.gridLayout_9.addWidget(self.label_29, 2, 0, 1, 1)
        self.pro5TTime = QtWidgets.QLineEdit(self.highVoltageTab)
        self.pro5TTime.setObjectName("pro5TTime")
        self.gridLayout_9.addWidget(self.pro5TTime, 2, 1, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_9, 0, 1, 1, 1)
        self.highSesList = QtWidgets.QListWidget(self.highVoltageTab)
        self.highSesList.setObjectName("highSesList")
        self.gridLayout_20.addWidget(self.highSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.highVoltageTab, "")
        self.manifoldTab = QtWidgets.QWidget()
        self.manifoldTab.setObjectName("manifoldTab")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.manifoldTab)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.manifoldComList = QtWidgets.QListWidget(self.manifoldTab)
        self.manifoldComList.setObjectName("manifoldComList")
        self.gridLayout_21.addWidget(self.manifoldComList, 0, 0, 2, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_33 = QtWidgets.QLabel(self.manifoldTab)
        self.label_33.setObjectName("label_33")
        self.gridLayout_10.addWidget(self.label_33, 0, 0, 1, 1)
        self.pro6STime = QtWidgets.QLineEdit(self.manifoldTab)
        self.pro6STime.setObjectName("pro6STime")
        self.gridLayout_10.addWidget(self.pro6STime, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.manifoldTab)
        self.label_34.setObjectName("label_34")
        self.gridLayout_10.addWidget(self.label_34, 1, 0, 1, 1)
        self.pro6ETime = QtWidgets.QLineEdit(self.manifoldTab)
        self.pro6ETime.setObjectName("pro6ETime")
        self.gridLayout_10.addWidget(self.pro6ETime, 1, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.manifoldTab)
        self.label_32.setObjectName("label_32")
        self.gridLayout_10.addWidget(self.label_32, 2, 0, 1, 1)
        self.pro6TTime = QtWidgets.QLineEdit(self.manifoldTab)
        self.pro6TTime.setObjectName("pro6TTime")
        self.gridLayout_10.addWidget(self.pro6TTime, 2, 1, 1, 1)
        self.gridLayout_21.addLayout(self.gridLayout_10, 0, 1, 1, 1)
        self.manifoldSesList = QtWidgets.QListWidget(self.manifoldTab)
        self.manifoldSesList.setObjectName("manifoldSesList")
        self.gridLayout_21.addWidget(self.manifoldSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.manifoldTab, "")
        self.floodingTab = QtWidgets.QWidget()
        self.floodingTab.setObjectName("floodingTab")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.floodingTab)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.floodingComList = QtWidgets.QListWidget(self.floodingTab)
        self.floodingComList.setObjectName("floodingComList")
        self.gridLayout_22.addWidget(self.floodingComList, 0, 0, 2, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_36 = QtWidgets.QLabel(self.floodingTab)
        self.label_36.setObjectName("label_36")
        self.gridLayout_11.addWidget(self.label_36, 0, 0, 1, 1)
        self.pro7STime = QtWidgets.QLineEdit(self.floodingTab)
        self.pro7STime.setObjectName("pro7STime")
        self.gridLayout_11.addWidget(self.pro7STime, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.floodingTab)
        self.label_37.setObjectName("label_37")
        self.gridLayout_11.addWidget(self.label_37, 1, 0, 1, 1)
        self.pro7ETime = QtWidgets.QLineEdit(self.floodingTab)
        self.pro7ETime.setObjectName("pro7ETime")
        self.gridLayout_11.addWidget(self.pro7ETime, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.floodingTab)
        self.label_35.setObjectName("label_35")
        self.gridLayout_11.addWidget(self.label_35, 2, 0, 1, 1)
        self.pro7TTime = QtWidgets.QLineEdit(self.floodingTab)
        self.pro7TTime.setObjectName("pro7TTime")
        self.gridLayout_11.addWidget(self.pro7TTime, 2, 1, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.floodingSesList = QtWidgets.QListWidget(self.floodingTab)
        self.floodingSesList.setObjectName("floodingSesList")
        self.gridLayout_22.addWidget(self.floodingSesList, 1, 1, 1, 1)
        self.tabWidget.addTab(self.floodingTab, "")
        self.finalQCTab = QtWidgets.QWidget()
        self.finalQCTab.setObjectName("finalQCTab")
        self.tabWidget.addTab(self.finalQCTab, "")
        self.storageTab = QtWidgets.QWidget()
        self.storageTab.setObjectName("storageTab")
        self.tabWidget.addTab(self.storageTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.splitter_3, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(1438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuExport = QtWidgets.QMenu(self.menuFile)
        self.menuExport.setObjectName("menuExport")
        self.menuHeat_Data_CSV = QtWidgets.QMenu(self.menuExport)
        self.menuHeat_Data_CSV.setObjectName("menuHeat_Data_CSV")
        self.menuExport_Graph = QtWidgets.QMenu(self.menuFile)
        self.menuExport_Graph.setObjectName("menuExport_Graph")
        self.menuHeat_Data = QtWidgets.QMenu(self.menuExport_Graph)
        self.menuHeat_Data.setObjectName("menuHeat_Data")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuColor_Scheme = QtWidgets.QMenu(self.menuView)
        self.menuColor_Scheme.setObjectName("menuColor_Scheme")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.actionHVCSV = QtWidgets.QAction(MainWindow)
        self.actionHVCSV.setObjectName("actionHVCSV")
        self.actionStrawCSV = QtWidgets.QAction(MainWindow)
        self.actionStrawCSV.setObjectName("actionStrawCSV")
        self.actionWireCSV = QtWidgets.QAction(MainWindow)
        self.actionWireCSV.setObjectName("actionWireCSV")
        self.actionAllCSV = QtWidgets.QAction(MainWindow)
        self.actionAllCSV.setObjectName("actionAllCSV")
        self.actionPro1HeatCSV = QtWidgets.QAction(MainWindow)
        self.actionPro1HeatCSV.setObjectName("actionPro1HeatCSV")
        self.actionPro2HeatCSV = QtWidgets.QAction(MainWindow)
        self.actionPro2HeatCSV.setObjectName("actionPro2HeatCSV")
        self.actionPro6HeatCSV = QtWidgets.QAction(MainWindow)
        self.actionPro6HeatCSV.setObjectName("actionPro6HeatCSV")
        self.actionAllHeatCSV = QtWidgets.QAction(MainWindow)
        self.actionAllHeatCSV.setObjectName("actionAllHeatCSV")
        self.actionGraph_Settings = QtWidgets.QAction(MainWindow)
        self.actionGraph_Settings.setObjectName("actionGraph_Settings")
        self.actionPro1HeatGraph = QtWidgets.QAction(MainWindow)
        self.actionPro1HeatGraph.setObjectName("actionPro1HeatGraph")
        self.actionPro2HeatGraph = QtWidgets.QAction(MainWindow)
        self.actionPro2HeatGraph.setObjectName("actionPro2HeatGraph")
        self.actionPro6HeatGraph = QtWidgets.QAction(MainWindow)
        self.actionPro6HeatGraph.setObjectName("actionPro6HeatGraph")
        self.actionHVGraph = QtWidgets.QAction(MainWindow)
        self.actionHVGraph.setObjectName("actionHVGraph")
        self.actionStrawGraph = QtWidgets.QAction(MainWindow)
        self.actionStrawGraph.setObjectName("actionStrawGraph")
        self.actionWireGraph = QtWidgets.QAction(MainWindow)
        self.actionWireGraph.setObjectName("actionWireGraph")
        self.actionExport_Panel_Report = QtWidgets.QAction(MainWindow)
        self.actionExport_Panel_Report.setObjectName("actionExport_Panel_Report")
        self.actionExport_Location = QtWidgets.QAction(MainWindow)
        self.actionExport_Location.setObjectName("actionExport_Location")
        self.actionDefault = QtWidgets.QAction(MainWindow)
        self.actionDefault.setObjectName("actionDefault")
        self.actionLight = QtWidgets.QAction(MainWindow)
        self.actionLight.setObjectName("actionLight")
        self.actionDark = QtWidgets.QAction(MainWindow)
        self.actionDark.setObjectName("actionDark")
        self.actionSend_Feedback_Issue = QtWidgets.QAction(MainWindow)
        self.actionSend_Feedback_Issue.setObjectName("actionSend_Feedback_Issue")
        self.actionDatabase_Location = QtWidgets.QAction(MainWindow)
        self.actionDatabase_Location.setObjectName("actionDatabase_Location")
        self.actionBlack = QtWidgets.QAction(MainWindow)
        self.actionBlack.setObjectName("actionBlack")
        self.actionGoldy = QtWidgets.QAction(MainWindow)
        self.actionGoldy.setObjectName("actionGoldy")
        self.actionSurprise_Me = QtWidgets.QAction(MainWindow)
        self.actionSurprise_Me.setObjectName("actionSurprise_Me")
        self.actionLatest_Changes = QtWidgets.QAction(MainWindow)
        self.actionLatest_Changes.setObjectName("actionLatest_Changes")
        self.menuHeat_Data_CSV.addAction(self.actionPro1HeatCSV)
        self.menuHeat_Data_CSV.addAction(self.actionPro2HeatCSV)
        self.menuHeat_Data_CSV.addAction(self.actionPro6HeatCSV)
        self.menuHeat_Data_CSV.addAction(self.actionAllHeatCSV)
        self.menuExport.addAction(self.menuHeat_Data_CSV.menuAction())
        self.menuExport.addAction(self.actionHVCSV)
        self.menuExport.addAction(self.actionStrawCSV)
        self.menuExport.addAction(self.actionWireCSV)
        self.menuExport.addAction(self.actionAllCSV)
        self.menuHeat_Data.addAction(self.actionPro1HeatGraph)
        self.menuHeat_Data.addAction(self.actionPro2HeatGraph)
        self.menuHeat_Data.addAction(self.actionPro6HeatGraph)
        self.menuExport_Graph.addAction(self.menuHeat_Data.menuAction())
        self.menuExport_Graph.addAction(self.actionHVGraph)
        self.menuExport_Graph.addAction(self.actionStrawGraph)
        self.menuExport_Graph.addAction(self.actionWireGraph)
        self.menuFile.addAction(self.menuExport.menuAction())
        self.menuFile.addAction(self.menuExport_Graph.menuAction())
        self.menuFile.addAction(self.actionExport_Panel_Report)
        self.menuEdit.addAction(self.actionGraph_Settings)
        self.menuEdit.addAction(self.actionExport_Location)
        self.menuEdit.addAction(self.actionDatabase_Location)
        self.menuColor_Scheme.addAction(self.actionDefault)
        self.menuColor_Scheme.addAction(self.actionBlack)
        self.menuColor_Scheme.addAction(self.actionGoldy)
        self.menuColor_Scheme.addAction(self.actionSurprise_Me)
        self.menuView.addAction(self.menuColor_Scheme.menuAction())
        self.menuHelp.addAction(self.actionSend_Feedback_Issue)
        self.menuHelp.addAction(self.actionLatest_Changes)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.heatProBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Panel ID"))
        self.panelLE.setPlaceholderText(_translate("MainWindow", "***"))
        self.submitPB.setText(_translate("MainWindow", "Submit"))
        self.label_2.setText(_translate("MainWindow", "MN___"))
        self.ringsSetupBox.setTitle(_translate("MainWindow", "Part IDs"))
        self.label_17.setText(_translate("MainWindow", "PAAS A"))
        self.label_18.setText(_translate("MainWindow", "PAAS B"))
        self.label_19.setText(_translate("MainWindow", "PAAS C"))
        self.label_3.setText(_translate("MainWindow", "Base Plate"))
        self.label_4.setText(_translate("MainWindow", "MIR"))
        self.label_5.setText(_translate("MainWindow", "BIR"))
        self.label_6.setText(_translate("MainWindow", "PIR LA"))
        self.label_7.setText(_translate("MainWindow", "PIR LB"))
        self.label_8.setText(_translate("MainWindow", "PIR LC"))
        self.label_9.setText(_translate("MainWindow", "PIR RA"))
        self.label_10.setText(_translate("MainWindow", "PIR RB"))
        self.label_11.setText(_translate("MainWindow", "PIR RC"))
        self.label_12.setText(_translate("MainWindow", "ALF 1"))
        self.label_13.setText(_translate("MainWindow", "ALF 2"))
        self.measurementsBox.setTitle(_translate("MainWindow", "Measurements"))
        self.wireTensionBox.setTitle(_translate("MainWindow", "Wire Tension Data"))
        self.wireExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotWireDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.hvCurrentBox.setTitle(_translate("MainWindow", "HV Current Data"))
        self.hvExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotHVDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.strawTensionBox.setTitle(_translate("MainWindow", "Straw Tension Data"))
        self.strawExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotStrawDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.groupBox.setTitle(_translate("MainWindow", "Heating Data"))
        self.heatProBox.setItemText(0, _translate("MainWindow", "Process 1 - Inner Rings"))
        self.heatProBox.setItemText(1, _translate("MainWindow", "Process 2 - Straws"))
        self.heatProBox.setItemText(2, _translate("MainWindow", "Process 6 - Manifold"))
        self.plotHeatDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.heatExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.commentBox.setTitle(_translate("MainWindow", "Comments, Procedure Duration, GUI Sessions"))
        self.label_14.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_15.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_16.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ringsTab), _translate("MainWindow", "1 - Rings"))
        self.label_22.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_20.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_21.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.strawsTab), _translate("MainWindow", "2 - Straws"))
        self.label_25.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_23.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_24.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.senseWireTab), _translate("MainWindow", "3 - Sense Wire"))
        self.label_28.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_26.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_27.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pinsTab), _translate("MainWindow", "4 - Pin Protectors"))
        self.label_30.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_31.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_29.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.highVoltageTab), _translate("MainWindow", "5 - HV"))
        self.label_33.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_34.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_32.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manifoldTab), _translate("MainWindow", "6 - Manifold"))
        self.label_36.setText(_translate("MainWindow", "Procedure Start Time"))
        self.label_37.setText(_translate("MainWindow", "Procedure End Time"))
        self.label_35.setText(_translate("MainWindow", "Elapsed Time"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.floodingTab), _translate("MainWindow", "7 - Flooding"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.finalQCTab), _translate("MainWindow", "8 - Final QC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.storageTab), _translate("MainWindow", "9 - Storage"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExport.setTitle(_translate("MainWindow", "Export CSV"))
        self.menuHeat_Data_CSV.setTitle(_translate("MainWindow", "Heat Data"))
        self.menuExport_Graph.setTitle(_translate("MainWindow", "Export Graph"))
        self.menuHeat_Data.setTitle(_translate("MainWindow", "Heat Data"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuColor_Scheme.setTitle(_translate("MainWindow", "Color Scheme"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionHVCSV.setText(_translate("MainWindow", "HV Data"))
        self.actionStrawCSV.setText(_translate("MainWindow", "Straw Data"))
        self.actionWireCSV.setText(_translate("MainWindow", "Wire Data"))
        self.actionAllCSV.setText(_translate("MainWindow", "All Bulk Data"))
        self.actionPro1HeatCSV.setText(_translate("MainWindow", "Process 1 - Inner Rings"))
        self.actionPro2HeatCSV.setText(_translate("MainWindow", "Process 2 - Straws"))
        self.actionPro6HeatCSV.setText(_translate("MainWindow", "Proces 6 - Manifold"))
        self.actionAllHeatCSV.setText(_translate("MainWindow", "All Heat Data"))
        self.actionGraph_Settings.setText(_translate("MainWindow", "Graph Settings"))
        self.actionPro1HeatGraph.setText(_translate("MainWindow", "Process 1 - Inner Rings"))
        self.actionPro2HeatGraph.setText(_translate("MainWindow", "Process 2 - Straws"))
        self.actionPro6HeatGraph.setText(_translate("MainWindow", "Process 6 - Manifold"))
        self.actionHVGraph.setText(_translate("MainWindow", "HV Data"))
        self.actionStrawGraph.setText(_translate("MainWindow", "Straw Data"))
        self.actionWireGraph.setText(_translate("MainWindow", "Wire Data"))
        self.actionExport_Panel_Report.setText(_translate("MainWindow", "Export Panel Report"))
        self.actionExport_Location.setText(_translate("MainWindow", "Export Location"))
        self.actionDefault.setText(_translate("MainWindow", "Default"))
        self.actionLight.setText(_translate("MainWindow", "Light"))
        self.actionDark.setText(_translate("MainWindow", "Dark"))
        self.actionSend_Feedback_Issue.setText(_translate("MainWindow", "Send Feedback/Issue"))
        self.actionDatabase_Location.setText(_translate("MainWindow", "Database Location"))
        self.actionBlack.setText(_translate("MainWindow", "Black"))
        self.actionGoldy.setText(_translate("MainWindow", "Goldy"))
        self.actionSurprise_Me.setText(_translate("MainWindow", "Surprise Me"))
        self.actionLatest_Changes.setText(_translate("MainWindow", "Latest Changes"))
