# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'facileDB.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.measurementsBox = QtWidgets.QGroupBox(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.measurementsBox.setFont(font)
        self.measurementsBox.setObjectName("measurementsBox")
        self.gridLayout = QtWidgets.QGridLayout(self.measurementsBox)
        self.gridLayout.setObjectName("gridLayout")
        self.wireTensionBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.wireTensionBox.setObjectName("wireTensionBox")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.wireTensionBox)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.wireListWidget = QtWidgets.QListWidget(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.wireListWidget.setFont(font)
        self.wireListWidget.setObjectName("wireListWidget")
        self.gridLayout_13.addWidget(self.wireListWidget, 0, 0, 1, 2)
        self.wireExportButton = QtWidgets.QPushButton(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.wireExportButton.setFont(font)
        self.wireExportButton.setObjectName("wireExportButton")
        self.gridLayout_13.addWidget(self.wireExportButton, 1, 0, 1, 1)
        self.plotWireDataButton = QtWidgets.QPushButton(self.wireTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotWireDataButton.setFont(font)
        self.plotWireDataButton.setObjectName("plotWireDataButton")
        self.gridLayout_13.addWidget(self.plotWireDataButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.wireTensionBox, 0, 3, 1, 1)
        self.hvCurrentBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.hvCurrentBox.setMinimumSize(QtCore.QSize(150, 0))
        self.hvCurrentBox.setObjectName("hvCurrentBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.hvCurrentBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.hvExportButton = QtWidgets.QPushButton(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.hvExportButton.setFont(font)
        self.hvExportButton.setObjectName("hvExportButton")
        self.gridLayout_3.addWidget(self.hvExportButton, 2, 0, 1, 1)
        self.hvListWidget = QtWidgets.QListWidget(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.hvListWidget.setFont(font)
        self.hvListWidget.setObjectName("hvListWidget")
        self.gridLayout_3.addWidget(self.hvListWidget, 0, 0, 1, 2)
        self.plotHVDataButton = QtWidgets.QPushButton(self.hvCurrentBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotHVDataButton.setFont(font)
        self.plotHVDataButton.setObjectName("plotHVDataButton")
        self.gridLayout_3.addWidget(self.plotHVDataButton, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.hvCurrentBox, 0, 1, 1, 1)
        self.strawTensionBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.strawTensionBox.setObjectName("strawTensionBox")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.strawTensionBox)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.strawListWidget = QtWidgets.QListWidget(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.strawListWidget.setFont(font)
        self.strawListWidget.setObjectName("strawListWidget")
        self.gridLayout_12.addWidget(self.strawListWidget, 0, 0, 1, 2)
        self.strawExportButton = QtWidgets.QPushButton(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.strawExportButton.setFont(font)
        self.strawExportButton.setObjectName("strawExportButton")
        self.gridLayout_12.addWidget(self.strawExportButton, 1, 0, 1, 1)
        self.plotStrawDataButton = QtWidgets.QPushButton(self.strawTensionBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotStrawDataButton.setFont(font)
        self.plotStrawDataButton.setObjectName("plotStrawDataButton")
        self.gridLayout_12.addWidget(self.plotStrawDataButton, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.strawTensionBox, 0, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.measurementsBox)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_14.addWidget(self.comboBox, 0, 0, 1, 2)
        self.plotHeatDataButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.plotHeatDataButton.setFont(font)
        self.plotHeatDataButton.setObjectName("plotHeatDataButton")
        self.gridLayout_14.addWidget(self.plotHeatDataButton, 2, 1, 1, 1)
        self.heatExportButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.heatExportButton.setFont(font)
        self.heatExportButton.setObjectName("heatExportButton")
        self.gridLayout_14.addWidget(self.heatExportButton, 2, 0, 1, 1)
        self.heatListWidget = QtWidgets.QListWidget(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.heatListWidget.setFont(font)
        self.heatListWidget.setObjectName("heatListWidget")
        self.gridLayout_14.addWidget(self.heatListWidget, 1, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.commentBox = QtWidgets.QGroupBox(self.splitter_3)
        self.commentBox.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.commentBox.setFont(font)
        self.commentBox.setObjectName("commentBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.commentBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.commentBox)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(730, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.ringsTab = QtWidgets.QWidget()
        self.ringsTab.setObjectName("ringsTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ringsTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.ringsComList = QtWidgets.QListWidget(self.ringsTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringsComList.sizePolicy().hasHeightForWidth())
        self.ringsComList.setSizePolicy(sizePolicy)
        self.ringsComList.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ringsComList.setFont(font)
        self.ringsComList.setObjectName("ringsComList")
        self.gridLayout_5.addWidget(self.ringsComList, 0, 2, 1, 1)
        self.tabWidget.addTab(self.ringsTab, "")
        self.strawsTab = QtWidgets.QWidget()
        self.strawsTab.setObjectName("strawsTab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.strawsTab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.strawsComList = QtWidgets.QListWidget(self.strawsTab)
        self.strawsComList.setObjectName("strawsComList")
        self.gridLayout_6.addWidget(self.strawsComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.strawsTab, "")
        self.senseWireTab = QtWidgets.QWidget()
        self.senseWireTab.setObjectName("senseWireTab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.senseWireTab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.senseComList = QtWidgets.QListWidget(self.senseWireTab)
        self.senseComList.setObjectName("senseComList")
        self.gridLayout_7.addWidget(self.senseComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.senseWireTab, "")
        self.pinsTab = QtWidgets.QWidget()
        self.pinsTab.setObjectName("pinsTab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.pinsTab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.pinsComList = QtWidgets.QListWidget(self.pinsTab)
        self.pinsComList.setObjectName("pinsComList")
        self.gridLayout_8.addWidget(self.pinsComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.pinsTab, "")
        self.highVoltageTab = QtWidgets.QWidget()
        self.highVoltageTab.setObjectName("highVoltageTab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.highVoltageTab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.highComList = QtWidgets.QListWidget(self.highVoltageTab)
        self.highComList.setObjectName("highComList")
        self.gridLayout_9.addWidget(self.highComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.highVoltageTab, "")
        self.manifoldTab = QtWidgets.QWidget()
        self.manifoldTab.setObjectName("manifoldTab")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.manifoldTab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.manifoldComList = QtWidgets.QListWidget(self.manifoldTab)
        self.manifoldComList.setObjectName("manifoldComList")
        self.gridLayout_10.addWidget(self.manifoldComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.manifoldTab, "")
        self.floodingTab = QtWidgets.QWidget()
        self.floodingTab.setObjectName("floodingTab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.floodingTab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.floodingComList = QtWidgets.QListWidget(self.floodingTab)
        self.floodingComList.setObjectName("floodingComList")
        self.gridLayout_11.addWidget(self.floodingComList, 0, 0, 1, 1)
        self.tabWidget.addTab(self.floodingTab, "")
        self.finalQCTab = QtWidgets.QWidget()
        self.finalQCTab.setObjectName("finalQCTab")
        self.tabWidget.addTab(self.finalQCTab, "")
        self.storageTab = QtWidgets.QWidget()
        self.storageTab.setObjectName("storageTab")
        self.tabWidget.addTab(self.storageTab, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.splitter_3, 1, 1, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.panelLE = QtWidgets.QLineEdit(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.panelLE.sizePolicy().hasHeightForWidth())
        self.panelLE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.panelLE.setFont(font)
        self.panelLE.setMaxLength(3)
        self.panelLE.setObjectName("panelLE")
        self.submitPB = QtWidgets.QPushButton(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submitPB.sizePolicy().hasHeightForWidth())
        self.submitPB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.submitPB.setFont(font)
        self.submitPB.setObjectName("submitPB")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_15.addWidget(self.splitter, 0, 0, 1, 2)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.ringsSetupBox = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ringsSetupBox.sizePolicy().hasHeightForWidth())
        self.ringsSetupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.ringsSetupBox.setFont(font)
        self.ringsSetupBox.setObjectName("ringsSetupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ringsSetupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 0, 0, 1, 1)
        self.partPaasALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPaasALE.setFont(font)
        self.partPaasALE.setReadOnly(True)
        self.partPaasALE.setObjectName("partPaasALE")
        self.gridLayout_4.addWidget(self.partPaasALE, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.partPaasBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPaasBLE.setFont(font)
        self.partPaasBLE.setReadOnly(True)
        self.partPaasBLE.setObjectName("partPaasBLE")
        self.gridLayout_4.addWidget(self.partPaasBLE, 1, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 2, 0, 1, 1)
        self.partPaasCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPaasCLE.setFont(font)
        self.partPaasCLE.setReadOnly(True)
        self.partPaasCLE.setObjectName("partPaasCLE")
        self.gridLayout_4.addWidget(self.partPaasCLE, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 3, 0, 1, 1)
        self.partBasePlateLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partBasePlateLE.setFont(font)
        self.partBasePlateLE.setReadOnly(True)
        self.partBasePlateLE.setObjectName("partBasePlateLE")
        self.gridLayout_4.addWidget(self.partBasePlateLE, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 4, 0, 1, 1)
        self.partMIRLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partMIRLE.setFont(font)
        self.partMIRLE.setReadOnly(True)
        self.partMIRLE.setObjectName("partMIRLE")
        self.gridLayout_4.addWidget(self.partMIRLE, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 5, 0, 1, 1)
        self.partBIRLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partBIRLE.setFont(font)
        self.partBIRLE.setReadOnly(True)
        self.partBIRLE.setObjectName("partBIRLE")
        self.gridLayout_4.addWidget(self.partBIRLE, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 6, 0, 1, 1)
        self.partPLALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPLALE.setFont(font)
        self.partPLALE.setReadOnly(True)
        self.partPLALE.setObjectName("partPLALE")
        self.gridLayout_4.addWidget(self.partPLALE, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 7, 0, 1, 1)
        self.partPLBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPLBLE.setFont(font)
        self.partPLBLE.setReadOnly(True)
        self.partPLBLE.setObjectName("partPLBLE")
        self.gridLayout_4.addWidget(self.partPLBLE, 7, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 8, 0, 1, 1)
        self.partPLCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPLCLE.setFont(font)
        self.partPLCLE.setReadOnly(True)
        self.partPLCLE.setObjectName("partPLCLE")
        self.gridLayout_4.addWidget(self.partPLCLE, 8, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 9, 0, 1, 1)
        self.partPRALE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPRALE.setFont(font)
        self.partPRALE.setReadOnly(True)
        self.partPRALE.setObjectName("partPRALE")
        self.gridLayout_4.addWidget(self.partPRALE, 9, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 10, 0, 1, 1)
        self.partPRBLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPRBLE.setFont(font)
        self.partPRBLE.setReadOnly(True)
        self.partPRBLE.setObjectName("partPRBLE")
        self.gridLayout_4.addWidget(self.partPRBLE, 10, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 11, 0, 1, 1)
        self.partPRCLE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partPRCLE.setFont(font)
        self.partPRCLE.setReadOnly(True)
        self.partPRCLE.setObjectName("partPRCLE")
        self.gridLayout_4.addWidget(self.partPRCLE, 11, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 12, 0, 1, 1)
        self.partALF1LE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partALF1LE.setFont(font)
        self.partALF1LE.setReadOnly(True)
        self.partALF1LE.setObjectName("partALF1LE")
        self.gridLayout_4.addWidget(self.partALF1LE, 12, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 13, 0, 1, 1)
        self.partALF2LE = QtWidgets.QLineEdit(self.ringsSetupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.partALF2LE.setFont(font)
        self.partALF2LE.setReadOnly(True)
        self.partALF2LE.setObjectName("partALF2LE")
        self.gridLayout_4.addWidget(self.partALF2LE, 13, 1, 1, 1)
        self.gridLayout_15.addWidget(self.splitter_2, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(1438, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1600, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.measurementsBox.setTitle(_translate("MainWindow", "Measurements"))
        self.wireTensionBox.setTitle(_translate("MainWindow", "Wire Tension Data"))
        self.wireExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotWireDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.hvCurrentBox.setTitle(_translate("MainWindow", "HV Current Data"))
        self.hvExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotHVDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.strawTensionBox.setTitle(_translate("MainWindow", "Straw Tension Data"))
        self.strawExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.plotStrawDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.groupBox.setTitle(_translate("MainWindow", "Heating Data"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Select Process"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Process 2 - Straws"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Process 6 - Manifold"))
        self.plotHeatDataButton.setText(_translate("MainWindow", "Plot On Graph"))
        self.heatExportButton.setText(_translate("MainWindow", "Export To CSV"))
        self.commentBox.setTitle(_translate("MainWindow", "Comments"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ringsTab), _translate("MainWindow", "1 - Rings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.strawsTab), _translate("MainWindow", "2 - Straws"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.senseWireTab), _translate("MainWindow", "3 - Sense Wire"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pinsTab), _translate("MainWindow", "4 - Pin Protectors"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.highVoltageTab), _translate("MainWindow", "5 - HV"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.manifoldTab), _translate("MainWindow", "6 - Manifold"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.floodingTab), _translate("MainWindow", "7 - Flooding"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.finalQCTab), _translate("MainWindow", "8 - Final QC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.storageTab), _translate("MainWindow", "9 - Storage"))
        self.label.setText(_translate("MainWindow", "Panel ID"))
        self.panelLE.setPlaceholderText(_translate("MainWindow", "***"))
        self.submitPB.setText(_translate("MainWindow", "Submit"))
        self.label_2.setText(_translate("MainWindow", "MN___"))
        self.ringsSetupBox.setTitle(_translate("MainWindow", "Part IDs"))
        self.label_17.setText(_translate("MainWindow", "PAAS A"))
        self.label_18.setText(_translate("MainWindow", "PAAS B"))
        self.label_19.setText(_translate("MainWindow", "PAAS C"))
        self.label_3.setText(_translate("MainWindow", "Base Plate"))
        self.label_4.setText(_translate("MainWindow", "MIR"))
        self.label_5.setText(_translate("MainWindow", "BIR"))
        self.label_6.setText(_translate("MainWindow", "PIR LA"))
        self.label_7.setText(_translate("MainWindow", "PIR LB"))
        self.label_8.setText(_translate("MainWindow", "PIR LC"))
        self.label_9.setText(_translate("MainWindow", "PIR RA"))
        self.label_10.setText(_translate("MainWindow", "PIR RB"))
        self.label_11.setText(_translate("MainWindow", "PIR RC"))
        self.label_12.setText(_translate("MainWindow", "ALF 1"))
        self.label_13.setText(_translate("MainWindow", "ALF 2"))
