# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remove.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialogw(object):
    def setupUi(self, Dialogw):
        Dialogw.setObjectName("Dialogw")
        Dialogw.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialogw.resize(386, 856)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialogw.sizePolicy().hasHeightForWidth())
        Dialogw.setSizePolicy(sizePolicy)
        Dialogw.setAutoFillBackground(True)
        Dialogw.setStyleSheet("")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialogw)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 101, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.straw_1 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_1.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_1.setFont(font)
        self.straw_1.setObjectName("straw_1")
        self.straw_2 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_2.setFont(font)
        self.straw_2.setObjectName("straw_2")
        self.straw_3 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_3.setGeometry(QtCore.QRect(10, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_3.setFont(font)
        self.straw_3.setObjectName("straw_3")
        self.straw_4 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_4.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_4.setFont(font)
        self.straw_4.setObjectName("straw_4")
        self.straw_5 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_5.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_5.setFont(font)
        self.straw_5.setObjectName("straw_5")
        self.straw_6 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_6.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_6.setFont(font)
        self.straw_6.setObjectName("straw_6")
        self.straw_7 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_7.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_7.setFont(font)
        self.straw_7.setObjectName("straw_7")
        self.straw_8 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_8.setGeometry(QtCore.QRect(10, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_8.setFont(font)
        self.straw_8.setObjectName("straw_8")
        self.straw_9 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_9.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_9.setFont(font)
        self.straw_9.setObjectName("straw_9")
        self.straw_10 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_10.setGeometry(QtCore.QRect(10, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_10.setFont(font)
        self.straw_10.setObjectName("straw_10")
        self.straw_11 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_11.setGeometry(QtCore.QRect(10, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_11.setFont(font)
        self.straw_11.setObjectName("straw_11")
        self.straw_12 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_12.setGeometry(QtCore.QRect(10, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_12.setFont(font)
        self.straw_12.setObjectName("straw_12")
        self.straw_13 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_13.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_13.setFont(font)
        self.straw_13.setObjectName("straw_13")
        self.straw_14 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_14.setGeometry(QtCore.QRect(10, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_14.setFont(font)
        self.straw_14.setObjectName("straw_14")
        self.straw_15 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_15.setGeometry(QtCore.QRect(10, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_15.setFont(font)
        self.straw_15.setObjectName("straw_15")
        self.straw_16 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_16.setGeometry(QtCore.QRect(10, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_16.setFont(font)
        self.straw_16.setObjectName("straw_16")
        self.straw_17 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_17.setGeometry(QtCore.QRect(10, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_17.setFont(font)
        self.straw_17.setObjectName("straw_17")
        self.straw_18 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_18.setGeometry(QtCore.QRect(10, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_18.setFont(font)
        self.straw_18.setObjectName("straw_18")
        self.straw_19 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_19.setGeometry(QtCore.QRect(10, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_19.setFont(font)
        self.straw_19.setObjectName("straw_19")
        self.straw_20 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_20.setGeometry(QtCore.QRect(10, 590, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_20.setFont(font)
        self.straw_20.setObjectName("straw_20")
        self.straw_21 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_21.setGeometry(QtCore.QRect(10, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_21.setFont(font)
        self.straw_21.setObjectName("straw_21")
        self.straw_22 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_22.setGeometry(QtCore.QRect(10, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_22.setFont(font)
        self.straw_22.setObjectName("straw_22")
        self.straw_23 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_23.setGeometry(QtCore.QRect(10, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_23.setFont(font)
        self.straw_23.setObjectName("straw_23")
        self.straw_24 = QtWidgets.QLabel(self.groupBox_2)
        self.straw_24.setGeometry(QtCore.QRect(10, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.straw_24.setFont(font)
        self.straw_24.setObjectName("straw_24")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialogw)
        self.groupBox_3.setGeometry(QtCore.QRect(130, 80, 101, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pf_1 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_1.setGeometry(QtCore.QRect(10, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_1.setFont(font)
        self.pf_1.setObjectName("pf_1")
        self.pf_2 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_2.setFont(font)
        self.pf_2.setObjectName("pf_2")
        self.pf_3 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_3.setGeometry(QtCore.QRect(10, 80, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_3.setFont(font)
        self.pf_3.setObjectName("pf_3")
        self.pf_4 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_4.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_4.setFont(font)
        self.pf_4.setObjectName("pf_4")
        self.pf_5 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_5.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_5.setFont(font)
        self.pf_5.setObjectName("pf_5")
        self.pf_6 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_6.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_6.setFont(font)
        self.pf_6.setObjectName("pf_6")
        self.pf_7 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_7.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_7.setFont(font)
        self.pf_7.setObjectName("pf_7")
        self.pf_8 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_8.setGeometry(QtCore.QRect(10, 230, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_8.setFont(font)
        self.pf_8.setObjectName("pf_8")
        self.pf_9 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_9.setGeometry(QtCore.QRect(10, 260, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_9.setFont(font)
        self.pf_9.setObjectName("pf_9")
        self.pf_10 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_10.setGeometry(QtCore.QRect(10, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_10.setFont(font)
        self.pf_10.setObjectName("pf_10")
        self.pf_11 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_11.setGeometry(QtCore.QRect(10, 320, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_11.setFont(font)
        self.pf_11.setObjectName("pf_11")
        self.pf_12 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_12.setGeometry(QtCore.QRect(10, 350, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_12.setFont(font)
        self.pf_12.setObjectName("pf_12")
        self.pf_13 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_13.setGeometry(QtCore.QRect(10, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_13.setFont(font)
        self.pf_13.setObjectName("pf_13")
        self.pf_14 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_14.setGeometry(QtCore.QRect(10, 410, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_14.setFont(font)
        self.pf_14.setObjectName("pf_14")
        self.pf_15 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_15.setGeometry(QtCore.QRect(10, 440, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_15.setFont(font)
        self.pf_15.setObjectName("pf_15")
        self.pf_16 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_16.setGeometry(QtCore.QRect(10, 470, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_16.setFont(font)
        self.pf_16.setObjectName("pf_16")
        self.pf_17 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_17.setGeometry(QtCore.QRect(10, 500, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_17.setFont(font)
        self.pf_17.setObjectName("pf_17")
        self.pf_18 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_18.setGeometry(QtCore.QRect(10, 530, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_18.setFont(font)
        self.pf_18.setObjectName("pf_18")
        self.pf_19 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_19.setGeometry(QtCore.QRect(10, 560, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_19.setFont(font)
        self.pf_19.setObjectName("pf_19")
        self.pf_20 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_20.setGeometry(QtCore.QRect(10, 590, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_20.setFont(font)
        self.pf_20.setObjectName("pf_20")
        self.pf_21 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_21.setGeometry(QtCore.QRect(10, 620, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_21.setFont(font)
        self.pf_21.setObjectName("pf_21")
        self.pf_22 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_22.setGeometry(QtCore.QRect(10, 650, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_22.setFont(font)
        self.pf_22.setObjectName("pf_22")
        self.pf_23 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_23.setGeometry(QtCore.QRect(10, 680, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_23.setFont(font)
        self.pf_23.setObjectName("pf_23")
        self.pf_24 = QtWidgets.QLabel(self.groupBox_3)
        self.pf_24.setGeometry(QtCore.QRect(10, 710, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.pf_24.setFont(font)
        self.pf_24.setObjectName("pf_24")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialogw)
        self.groupBox_4.setGeometry(QtCore.QRect(240, 80, 131, 761))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.remove_1 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_1.setGeometry(QtCore.QRect(10, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_1.setFont(font)
        self.remove_1.setObjectName("remove_1")
        self.removeButtons = QtWidgets.QButtonGroup(Dialogw)
        self.removeButtons.setObjectName("removeButtons")
        self.removeButtons.addButton(self.remove_1)
        self.remove_2 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_2.setGeometry(QtCore.QRect(10, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_2.setFont(font)
        self.remove_2.setObjectName("remove_2")
        self.removeButtons.addButton(self.remove_2)
        self.remove_3 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_3.setGeometry(QtCore.QRect(10, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_3.setFont(font)
        self.remove_3.setObjectName("remove_3")
        self.removeButtons.addButton(self.remove_3)
        self.remove_4 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_4.setGeometry(QtCore.QRect(10, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_4.setFont(font)
        self.remove_4.setObjectName("remove_4")
        self.removeButtons.addButton(self.remove_4)
        self.remove_5 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_5.setGeometry(QtCore.QRect(10, 140, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_5.setFont(font)
        self.remove_5.setObjectName("remove_5")
        self.removeButtons.addButton(self.remove_5)
        self.remove_6 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_6.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_6.setFont(font)
        self.remove_6.setObjectName("remove_6")
        self.removeButtons.addButton(self.remove_6)
        self.remove_7 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_7.setGeometry(QtCore.QRect(10, 200, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_7.setFont(font)
        self.remove_7.setObjectName("remove_7")
        self.removeButtons.addButton(self.remove_7)
        self.remove_8 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_8.setGeometry(QtCore.QRect(10, 230, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_8.setFont(font)
        self.remove_8.setObjectName("remove_8")
        self.removeButtons.addButton(self.remove_8)
        self.remove_9 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_9.setGeometry(QtCore.QRect(10, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_9.setFont(font)
        self.remove_9.setObjectName("remove_9")
        self.removeButtons.addButton(self.remove_9)
        self.remove_10 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_10.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_10.setFont(font)
        self.remove_10.setObjectName("remove_10")
        self.removeButtons.addButton(self.remove_10)
        self.remove_11 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_11.setGeometry(QtCore.QRect(10, 320, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_11.setFont(font)
        self.remove_11.setObjectName("remove_11")
        self.removeButtons.addButton(self.remove_11)
        self.remove_12 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_12.setGeometry(QtCore.QRect(10, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_12.setFont(font)
        self.remove_12.setObjectName("remove_12")
        self.removeButtons.addButton(self.remove_12)
        self.remove_13 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_13.setGeometry(QtCore.QRect(10, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_13.setFont(font)
        self.remove_13.setObjectName("remove_13")
        self.removeButtons.addButton(self.remove_13)
        self.remove_14 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_14.setGeometry(QtCore.QRect(10, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_14.setFont(font)
        self.remove_14.setObjectName("remove_14")
        self.removeButtons.addButton(self.remove_14)
        self.remove_15 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_15.setGeometry(QtCore.QRect(10, 440, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_15.setFont(font)
        self.remove_15.setObjectName("remove_15")
        self.removeButtons.addButton(self.remove_15)
        self.remove_16 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_16.setGeometry(QtCore.QRect(10, 470, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_16.setFont(font)
        self.remove_16.setObjectName("remove_16")
        self.removeButtons.addButton(self.remove_16)
        self.remove_17 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_17.setGeometry(QtCore.QRect(10, 500, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_17.setFont(font)
        self.remove_17.setObjectName("remove_17")
        self.removeButtons.addButton(self.remove_17)
        self.remove_18 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_18.setGeometry(QtCore.QRect(10, 530, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_18.setFont(font)
        self.remove_18.setObjectName("remove_18")
        self.removeButtons.addButton(self.remove_18)
        self.remove_19 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_19.setGeometry(QtCore.QRect(10, 560, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_19.setFont(font)
        self.remove_19.setObjectName("remove_19")
        self.removeButtons.addButton(self.remove_19)
        self.remove_20 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_20.setGeometry(QtCore.QRect(10, 590, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_20.setFont(font)
        self.remove_20.setObjectName("remove_20")
        self.removeButtons.addButton(self.remove_20)
        self.remove_21 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_21.setGeometry(QtCore.QRect(10, 620, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_21.setFont(font)
        self.remove_21.setObjectName("remove_21")
        self.removeButtons.addButton(self.remove_21)
        self.remove_22 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_22.setGeometry(QtCore.QRect(10, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_22.setFont(font)
        self.remove_22.setObjectName("remove_22")
        self.removeButtons.addButton(self.remove_22)
        self.remove_23 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_23.setGeometry(QtCore.QRect(10, 680, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_23.setFont(font)
        self.remove_23.setObjectName("remove_23")
        self.removeButtons.addButton(self.remove_23)
        self.remove_24 = QtWidgets.QPushButton(self.groupBox_4)
        self.remove_24.setGeometry(QtCore.QRect(10, 710, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remove_24.setFont(font)
        self.remove_24.setObjectName("remove_24")
        self.removeButtons.addButton(self.remove_24)
        self.palletLabel = QtWidgets.QLabel(Dialogw)
        self.palletLabel.setGeometry(QtCore.QRect(80, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.palletLabel.setFont(font)
        self.palletLabel.setObjectName("palletLabel")
        self.lastLabel = QtWidgets.QLabel(Dialogw)
        self.lastLabel.setGeometry(QtCore.QRect(80, 40, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lastLabel.setFont(font)
        self.lastLabel.setObjectName("lastLabel")

        self.retranslateUi(Dialogw)
        QtCore.QMetaObject.connectSlotsByName(Dialogw)

    def retranslateUi(self, Dialogw):
        _translate = QtCore.QCoreApplication.translate
        Dialogw.setWindowTitle(_translate("Dialogw", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialogw", "Straw"))
        self.straw_1.setText(_translate("Dialogw", "Straw"))
        self.straw_2.setText(_translate("Dialogw", "Straw"))
        self.straw_3.setText(_translate("Dialogw", "Straw"))
        self.straw_4.setText(_translate("Dialogw", "Straw"))
        self.straw_5.setText(_translate("Dialogw", "Straw"))
        self.straw_6.setText(_translate("Dialogw", "Straw"))
        self.straw_7.setText(_translate("Dialogw", "Straw"))
        self.straw_8.setText(_translate("Dialogw", "Straw"))
        self.straw_9.setText(_translate("Dialogw", "Straw"))
        self.straw_10.setText(_translate("Dialogw", "Straw"))
        self.straw_11.setText(_translate("Dialogw", "Straw"))
        self.straw_12.setText(_translate("Dialogw", "Straw"))
        self.straw_13.setText(_translate("Dialogw", "Straw"))
        self.straw_14.setText(_translate("Dialogw", "Straw"))
        self.straw_15.setText(_translate("Dialogw", "Straw"))
        self.straw_16.setText(_translate("Dialogw", "Straw"))
        self.straw_17.setText(_translate("Dialogw", "Straw"))
        self.straw_18.setText(_translate("Dialogw", "Straw"))
        self.straw_19.setText(_translate("Dialogw", "Straw"))
        self.straw_20.setText(_translate("Dialogw", "Straw"))
        self.straw_21.setText(_translate("Dialogw", "Straw"))
        self.straw_22.setText(_translate("Dialogw", "Straw"))
        self.straw_23.setText(_translate("Dialogw", "Straw"))
        self.straw_24.setText(_translate("Dialogw", "Straw"))
        self.groupBox_3.setTitle(_translate("Dialogw", "Pass/Fail"))
        self.pf_1.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_2.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_3.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_4.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_5.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_6.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_7.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_8.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_9.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_10.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_11.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_12.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_13.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_14.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_15.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_16.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_17.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_18.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_19.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_20.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_21.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_22.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_23.setText(_translate("Dialogw", "Pass/Fail"))
        self.pf_24.setText(_translate("Dialogw", "Pass/Fail"))
        self.groupBox_4.setTitle(_translate("Dialogw", "Remove Straw"))
        self.remove_1.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_2.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_3.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_4.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_5.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_6.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_7.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_8.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_9.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_10.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_11.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_12.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_13.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_14.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_15.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_16.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_17.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_18.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_19.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_20.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_21.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_22.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_23.setText(_translate("Dialogw", "Remove Straw"))
        self.remove_24.setText(_translate("Dialogw", "Remove Straw"))
        self.palletLabel.setText(_translate("Dialogw", "Pallet:"))
        self.lastLabel.setText(_translate("Dialogw", "Last Step:"))

